### ISSUE TITLE
Auroracle tentacle ceiling can be clipped through

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#10]
I had Frostspark Boots and Bundle of Balloons, and managed to clip through the tentacle ceiling Auroracle summons. Will try to recreate this.

**Comment by TotallyNotAScalie** [comment]
Made the hitbox for this ~4x as tall, should prevent most speed-based clips within reason

**Comment by egshels** [comment]
Please submit a pull request before closing issues for this repository.

**Comment by TotallyNotAScalie** [comment]
Changes have already been pushed.

**Comment by egshels** [comment]
Changes on your fork do not translate to this repository.

**Comment by InvalidOS** [comment]
I managed to replicate it again somehow. I think I got hit and the knockback may have allowed me to clip through.

**Comment by InvalidOS** [comment]
I finally found out what causes this issue. During the player's iframes, they can clip through.
