### ISSUE TITLE
Going into windowed mode will misalign the Tincture slot

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#105]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The Tincture slot stays where it's supposed to, right under the camera sign
	Actual behavior: 
![20211020220221_1](https://user-images.githubusercontent.com/92499684/138198497-ef78c151-2ef9-4db0-841c-bc0f8c0cfd67.jpg)
Context: Was testing the Tincture mechanic

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Census, Recipe Browser, Boss Checklist, HERO's Mod, SLR
		Config settings: Default
		Game settings: Windowed
		Gameplay events happening: Absolutely nothing
		Your inputs: Going windowed to test the UI
		OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7385433/client.log)

Edit: It seems like tabbing out while windowed makes the Tincture slot stay like that even when going fullscreen.

**Comment by ScalarVector1** [comment]
Fixed in c9d4fcbb42a94bf14abe8f4cecece09bc703c369
