### ISSUE TITLE
Auroracle doesn't despawn when the player dies

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#11]
self-explanatory

**Comment by TotallyNotAScalie** [comment]
Can not reproduce -- can you provide any additional repo steps? Was your spawn point close enough to the arena it could have still registered you as in-range?

**Comment by InvalidOS** [comment]
My spawnpoint wasn't anywhere close to the arena. It was the default spawnpoint.
The seed was "c4", large world, crimson.
I was also on Expert difficulty when this occurred.

**Comment by ScalarVector1** [comment]
I have still been unable to reproduce this error. I am going to close this for now, if you can recreate this issue again reproducibly please reopen the issue.
