### ISSUE TITLE
Softlock when fighting Ceiros

### ISSUE THREAD

**Issue by WH0SB01** [ProjectStarlight/StarlightRiver#114]
## Issue Description
	Expected behavior: Ceiros first hp bar down, supposed to enter "second" phase (chains around the hp bar)
	Actual behavior: boss fight just fully froze, nothing moving at all
	Context: was running around on the ground and alt tabbed to discord right as he entered the second phase, was using flare breacher
	Error message (if applicable): none, nothing that is part of the mod will move

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Boss checklist, cheat sheet, HEROs mod, recipe browser, starlight river (obviously), worldgenpreviewer
		Config settings: default settings
		Game settings: 200% zoom, 120% ui scale, 2560x1440 resolution windowed fullscreen, 60% parralax, white lighting, auto quality, background blood and gore heat distortion storm effects enabled, high waves quality, multicore lighting off.
		Gameplay events happening: fighting Ceiros with flare breacher, as he entered his second "phase" with the chains around his hp bar i tabbed out of terraria and the boss fight froze (in normal difficulty) 
		Your inputs: shot ceiros with flare breacher, jumped down a platform, ran to the left i believe for a second, CLICKED out of the game instead of alt tabbing and he immediately entered his second form
		OS: windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7426354/client.log)

**Comment by ScalarVector1** [comment]
67033a45f2836e2a3dc8f81cc34825b8016479b3 should prevent this
