### ISSUE TITLE
Twisted Greatsword no SFX nor stamina cost when used outside the hotbar

### ISSUE THREAD

**Issue by Haidex** [ProjectStarlight/StarlightRiver#115]
## Issue Description
    ##Expected behavior: Twisted Greatsword should have SFX and consume it's custom stamina when used outside hotbar.
    Actual behavior: It did not had the swing SFX (only the hit one) and it's custom stamina says it's around 15% all the time when used outside the hotbar but it does not consume it meaning you can use it forever.
    Context: Just testing the weapons around.

## Reproduction
        Mod list: Starlight River, Full Health Respawn, Terry's Boss Timer, Boss Checklist, HP Awareness, Fargo's Mutant Mod, Shorter Respawn Time, AutoReforge, Cheat Sheet, AlchemistNPC Lite, Recipe Browser, Boss Cursor and Yet Another Boss Health Bar
        Config settings: Default settings
        Game settings: 100% zoom, 100% ui scale, 1920x1051 windowed fullscreen, 60% parallax, white lighting white, frame skip on, auto quality, background blood and gore heat distortion storm effects enabled, high waves quality, multicore lighting 2.
        Gameplay events happening: Testing weapons around on the spawn area
        Your inputs: Select the Twisted Greatsword with the cursor, drag it outside the inventory and right click to use it.
        OS: win 10

**Comment by ScalarVector1** [comment]
fixed in 3322d5aaecaa01fe39b8aa7fa5c35890405c7718
