### ISSUE TITLE
Mod cannot load on MacOS and Linux

### ISSUE THREAD

**Issue by just-another-player** [ProjectStarlight/StarlightRiver#116]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: [what was supposed to happen?]
	Actual behavior: [what did happen?]
	Context: [what else happened around this? When did it happen?]
	Error message (if applicable): [what did the game think was wrong?]

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: [what mods you have loaded]
		Config settings: [the config settings for Starlight River]
		Game settings: [the settings for the game, things such as zoom, lighting mode, etc]
		Gameplay events happening: [whats going on? were you fighting a boss? mining ores? AFKing?]
		Your inputs: [what you did precisely to trigger the issue. EX: running to the left and using the thunderbuss to the right]
		OS: [what OS are you on?]

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

**Comment by just-another-player** [comment]
<img width="1192" alt="Screen Shot 2021-11-03 at 8 26 26 am" src="https://user-images.githubusercontent.com/93621951/139953962-2ae7c2da-818f-4183-bc5d-3d7a61017c45.png">

**Comment by just-another-player** [comment]
<img width="1180" alt="Screen Shot 2021-11-03 at 8 27 09 am" src="https://user-images.githubusercontent.com/93621951/139954024-9b6dc5d9-2c51-4fee-8637-18dc685b0f1b.png">

**Comment by just-another-player** [comment]
i have tried this 5 times
this is what keeps happening
I have no other mods on

**Comment by Thorium0** [comment]
+1 I have the same issue

**Comment by chipgeekjr** [comment]
Same issue on MacOS 11.6, no mods other than this one enabled.
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7501610/client.log)

**Comment by ScalarVector1** [comment]
Primary cause of this issue appears to be differences in the compiled IL code between these versions and the windows version cause some patches to fail. Further investigation will be required to find all of these problematic patches and create alternative patches which support these versions.

**Comment by jkk752** [comment]
> Primary cause of this issue appears to be differences in the compiled IL code between these versions and the windows version cause some patches to fail. Further investigation will be required to find all of these problematic patches and create alternative patches which support these versions.

So I can not use it until the next modification?

**Comment by nttainBaka** [comment]
![Captura de tela de 2021-11-16 18-15-01](https://user-images.githubusercontent.com/86338617/142074164-89b9c09e-ff3b-41a1-9ccc-b230e49d1e0a.png)
samething on linux fedora 34

**Comment by ScalarVector1** [comment]
https://github.com/ProjectStarlight/StarlightRiver/pull/144 has a number of fixes which should resolve this, still need confirmation for macOS platforms

**Comment by ScalarVector1** [comment]
Closing this as this has been confirmed to be resolved
