### ISSUE TITLE
Download link not accessible.

### ISSUE THREAD

**Issue by firebranches** [ProjectStarlight/StarlightRiver#119]
The download link you sent is either gone or deleted because when I tried to get in, it said: ERROR 404. 
![dropbox error](https://user-images.githubusercontent.com/54911631/140584174-3a048496-e7c7-4f0e-af0d-73c1e9f2e606.png)

**Comment by ScalarVector1** [comment]
Resolved -- in the future please submit issue reports following the proper format.
