### ISSUE TITLE
Auroralings can cause unfair deaths against Auroracle's laser attack 

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#12]
Auroralings knocking you off of a platform you're using to block Auroracle's laser can make you want to tear your hair out. It feels straight up unfair.

**Comment by TotallyNotAScalie** [comment]
Auroralings no longer cause knockback, though auroraborn still will as only one spawns per cluster.

**Comment by egshels** [comment]
Please submit a pull request before closing issues for this repository.
