### ISSUE TITLE
Drill Containment Unit does not properly block item use

### ISSUE THREAD

**Issue by Dark-Starr** [ProjectStarlight/StarlightRiver#122]
## Issue Description
	Expected behavior: I expected the DCU to function normally, and cancel all held items' effects.
	Actual behavior: 1- Twisted Greatsword's energy was being used. 2- Twisted Greatsword's VFX started playing. 3- Datsuzei activated with a single press of my down key (S)... I also think it wasn't fully charged?
	Context: The DCU was not working, and Twisted Greatsword was attacking.
	Error message (if applicable): Nothing crashed.

## Reproduction
		Mod list: Boss Checklist, Boss Cursor, YABHB, HERO's mod, Magic Storage (all three versions, I don't know why), Recipe Browser, Starlight River Demo, Unofficial Calamity Mod Music, VeinMiner, Fargo's Mutant Mod.
		Config settings: Default
		Game settings: Grid on, Colour lighting, everything else default
		Gameplay events happening: Mining with Drill Containment Unit
		Your inputs: 1- Using Twisted Greatsword while in the DCU. 2- Using Twisted Greatsword before mounting the DCU. 3- Attempting to use Datsuzei while in the DCU.
		OS: Windows 10

## Additional context and log files
	Here is my [client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7492828/client.log) file.
	I loaded a pre-made world with these mods on, to see how badly it would break.
	*Did I do it right?*

**Comment by Dark-Starr** [comment]
One more tiny thing I forgot- having Twisted Greatsword in your inventory while mining down with DCU causes it to stutter its movement a bit

**Comment by ScalarVector1** [comment]
Fixed in https://github.com/ProjectStarlight/StarlightRiver/pull/142
