### ISSUE TITLE
It told me too

### ISSUE THREAD

**Issue by KitCat66** [ProjectStarlight/StarlightRiver#123]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Not bad food
	Actual behavior: Bad food
	Context: when i ate the consumable

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River, hero's mod v0.3.6.2
		Config settings: Default
		Game settings: 
		Gameplay events happening: eating the consumable
		Your inputs: LMB while holding the consumable
		OS: Windowes 10
		
![image](https://user-images.githubusercontent.com/93891180/140669802-51699195-3ed0-423f-a71a-2e2cf3a669f0.png)

**Comment by ScalarVector1** [comment]
Intended behavior, food spawned via cheat menus is and should be invalid.
