### ISSUE TITLE
Arena still scrolls after i died

### ISSUE THREAD

**Issue by pinbal-wizard** [ProjectStarlight/StarlightRiver#128]
## Issue Description
**The arena stayed scrolling after i died**
	Expected behavior: the arena stop scrolling
	Actual behavior: it stayed scrolling
	Context: i died and killed the boss at the same time i think
	

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: CheatSheet, ControlTrash, Luiafk, OmniSwing, SmartDoors, StarlightRiver
		Config settings: idk default 
		Game settings: default 
		Gameplay events happening: i died and killed the boss with the flare breacher 
		Your inputs: die and kill the boss with the delayed explosion on the flare breacher
		OS: windows 10

## Additional context and log files

https://user-images.githubusercontent.com/68714330/141625396-17924317-8435-45db-8677-d19baa02d87b.mp4

**yes i know i have cheat sheet boss was too hard.**

**Comment by ScalarVector1** [comment]
3658aaa92262fff696189a42510e18c8f1a4ef78 should prevent this and similar behavior
