### ISSUE TITLE
Ceiros arena can be mined but can't be placed back

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#13]
arena sprite is very funny

**Comment by TotallyNotAScalie** [comment]
Fixed with the implementation of boss arena build protection
![NoBuild](https://user-images.githubusercontent.com/5168952/119300405-b409f100-bc2e-11eb-9f59-34b56828a51a.gif)

**Comment by egshels** [comment]
Please submit a pull request before closing issues for this repository.
