### ISSUE TITLE
generation problem

### ISSUE THREAD

**Issue by tassador** [ProjectStarlight/StarlightRiver#130]
## Issue Description
When I launch the creation of the map there is a problem in the creation of the map spécifically in vitric desert
	
![image](https://user-images.githubusercontent.com/94358245/141756588-b730b089-0e20-49ed-8ddc-e55e6c2880f6.png)

## Reproduction
I just have the starlight mod downloaded on the discord server
Config settings: default
Gameplay events happening: map dose not charge
Your inputs: I created a new charater and a new map
OS: windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7537470/client.log)

thanks in advance for your help
and sorry for my bad english I may have done mistakes

**Comment by ScalarVector1** [comment]
This has already been fixed in https://github.com/ProjectStarlight/StarlightRiver/commit/c12095ba2cf5dde74f37e8b5141bb40241e09a80, this fix will come in the next patch. For now the best workaround is to generate a world on the 32bit modloader instead of the unofficial 64bit modloader.

**Comment by tassador** [comment]
thank you very much
