### ISSUE TITLE
Ceiros not aiming at you phase 2 attack

### ISSUE THREAD

**Issue by Haidex** [ProjectStarlight/StarlightRiver#133]
## Issue Description

 Ceiros looks at you but does not aim at you the glass spikes barrage attack, the telegraph also does not aim at you

## Reproduction
		Mod list: Starlight river
		Config settings: default
		Game settings: default
		Gameplay events happening: ocurred multiple times during Ceiros second phase 
		Your inputs: both staying still and moving arond result on the same bug
		OS: win10

**Comment by ScalarVector1** [comment]
Fixed in https://github.com/ProjectStarlight/StarlightRiver/pull/142
