### ISSUE TITLE
Plataforms still moving after ceiros dies

### ISSUE THREAD

**Issue by Haidex** [ProjectStarlight/StarlightRiver#134]
## Issue Description

After the player dies if the boss dies for the barbed knife debuff instead of despawning normally the plataforms keep moving even when spawning ceiros again afterwards, dying without killing ceiros with the debuff fixes the bug

## Reproduction

Ceiros must die when you're also dead, i have not tested if it happens with other debuffs but i managed to get it consistently to times under the same conditions

**Comment by ScalarVector1** [comment]
fixed in https://github.com/ProjectStarlight/StarlightRiver/pull/142
