### ISSUE TITLE
Can't kill boss?

### ISSUE THREAD

**Issue by Darqxs** [ProjectStarlight/StarlightRiver#135]
I was fighting the boss and his HP was not dropping below 7714 I thought it was just because it was an immortality phase which it was, but he healed after it and I dropped him to 7714 HP again but his HP would just loop because he was healing so I could never kill him.

I was only using the Starlight River mod

**Comment by ScalarVector1** [comment]
This is intended behavior. When the boss reaches certain HP gates during the first phase you are required to dash into a crystal which will turn blue and glow to progress the fight. Failing to do so within a set time frame will cause the boss to heal as intended.
