### ISSUE TITLE
some textures are appearing black on multiplayer and a random red banner appeared

### ISSUE THREAD

**Issue by dottedboxguy** [ProjectStarlight/StarlightRiver#138]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: every texture should appear fine
	Actual behavior: the textures of all the crystals (exept the ones you have to dash into) were black, and the walls of the ceiros arena too, but they kept their shape, they weren't giant black rectangles (go see images below), and a red banner appeared to the left of the ceiros arena for some reason (no one placed it and there were no blocks that we could break to make it disappear)
	Context: launching a multiplayer world and joining it
	Error message (if applicable): none

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: starlight river, cheat sheet
		Config settings: no modifications
		Game settings:  no modifs, 1080p
		Gameplay events happening: going outside the spawning area, and watching around (it was pretty obvious that smth was off ngl)
		Your inputs: creating a new world, hosting a multiplayer lobby, joining in, going outside the spawning area
		OS: Windows 10

## Additional context and log file
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627403/client.log)
[server.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627405/server.log)
![image](https://user-images.githubusercontent.com/92449077/144092674-3feef8cc-2924-40f6-b61f-aad2129ae4c0.png)
![image](https://user-images.githubusercontent.com/92449077/144092700-3eb4246d-d058-483b-b31f-368d49fffba9.png)

**Comment by TripleFate** [comment]
should be fixed in #157, retest in next demo build
