### ISSUE TITLE
More Twisted Greatsword and Drill Containment Unit bugs on multiplayer

### ISSUE THREAD

**Issue by Dark-Starr** [ProjectStarlight/StarlightRiver#139]
## Issue Description
	Expected behavior: I expected both items mentioned in the title to function normally
	Actual behavior: Twisted Greatsword's sound plays multiple times when used from the inventory(1), Sentinel Tincture does not rotate with either Ripshatter or Drill Containment unit(2), and the spawn area's cutout disappears rarely(3)
	Context: I was testing things that were broken in the previous demo build

## Reproduction
		Mod list: Boss Cursor, Starlight River, YABHB, and Cheat Sheet
		Config settings: Default
		Game settings: Colour lighting, cursor grid visible, the rest default
		Gameplay events happening: Using the Drill Containment Unit to see if any arena blocks could be mined
		Your inputs: Using Twisted Greatsword from the inventory(1), mounting the Drill Containment Unit with the Sentinel Tincture(2), and I just opened a world(3)
		OS: Windows 10

## Additional context and log files
**I'm not sure how to recreate the third bug listed here, so it might just be a one-time thing. I'm reporting it anyways to be safe.** 
		Here are my logs:
		[server.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627423/server.log)
		[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627424/client.log)

**Comment by ScalarVector1** [comment]
Fixed in https://github.com/ProjectStarlight/StarlightRiver/pull/142
