### ISSUE TITLE
Worldgen hangs on "Hiding Codex" step on seed "cum"

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#14]
cum seed breaks slr :trollface: 

crimson world, expert mode

**Comment by TotallyNotAScalie** [comment]
Note: Likely has nothing to do with this step, but rather somthing in PostWorldgen. This is the last step and thus the last message to appear

**Comment by TotallyNotAScalie** [comment]
I also need world size to attempt to reproduce this error.

**Comment by InvalidOS** [comment]
probably either medium or expert, can't remember which though

**Comment by InvalidOS** [comment]
medium or LARGE fuck

**Comment by InvalidOS** [comment]
ignore my brain breaking

**Comment by InvalidOS** [comment]
went back to try and replicate this behavior
settings: large world size, expert difficulty, crimson

**Comment by ScalarVector1** [comment]
Closing as this is ancient and has no hopes of being reproduced currently
