### ISSUE TITLE
platform spawning animation jittering a bit when breaking the crystal of the boss altar 

### ISSUE THREAD

**Issue by dottedboxguy** [ProjectStarlight/StarlightRiver#140]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: platform spawning animation should work fine, platform moves up following the background
	Actual behavior: background gone up like it should, but the platforms following it jittered around a bit, and players could go through them and fall sometime
	Context: dashing into the boss altar to make the platforms and background go up to fight ceiros in multiplayer
	Error message (if applicable): none

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: starlight river, cheat sheet
		Config settings: no modifs
		Game settings: mo modifs except for controls, 1080p
		Gameplay events happening: nothing outside of dashing in the altar
		Your inputs: starting to host a multiplayer server, going in, going outside of spawn, dashing in the boss altar, watching the platforms during the animation glith out a bit, going on them, falling

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627526/client.log)
[server.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627527/server.log)

**Comment by ScalarVector1** [comment]
Fallthrough issue fixed in https://github.com/ProjectStarlight/StarlightRiver/pull/142, jittering still stands

**Comment by ScalarVector1** [comment]
Closing this as there is not much more actionable to do here I believe.
