### ISSUE TITLE
Ceiros and Vitric enemy bugs in multiplayer

### ISSUE THREAD

**Issue by Dark-Starr** [ProjectStarlight/StarlightRiver#141]
## Issue Description
	Expected behavior: Ceiros' death drama not crashing my game(1), Fire Fly screenshake being normal strength(2), and generally Ceiros' fight being normal(3)
	Actual behavior: Ceiros' death drama crashed my game, Fire Flies can randomly shake your screen 5x the normal value, and three Resonant Crystals disappeared on Ceiros' final invincibility phase (I had to spawn one in with Cheat Sheet).
	Context: Fighting Ceiros in multiplayer, I was not the host.
	Error message (if applicable): [I hope the logs still have the error message because I can't remember for the life of me.]

## Reproduction
		Mod list: Boss Cursor, Starlight River, YABHB, and Cheat Sheet
		Config settings: Default
		Game settings: Colour lighting, cursor grid on, the rest is default
		Gameplay events happening: Fighting Ceiros (1 and 3), and killing Vitric enemies with 30x spawn rate (2)
		Your inputs: Killing Ceiros with Fetid... those things, while being hooked to four platforms using Lunar Hook

## Additional context and log files
**I just crashed while AFKing, ran out of memory, so I'm not sure if logs are affected. I had not restarted my world after discovering the spawn area cutout being weird, so maybe that's why?** 
Logs 👍 
[server.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627519/server.log)
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7627520/client.log)
A screenshot of the Resonant Crystals just not existing.
![20211130113416_1](https://user-images.githubusercontent.com/93879512/144096038-46020e3a-a571-47c9-8aaf-2bf11429b26c.jpg)
And of course, Ceiros' warp bubble not disappearing after his death.
![20211130112453_1](https://user-images.githubusercontent.com/93879512/144096399-9e529474-fc85-4607-bbc3-2bcc899dd064.jpg)
Side note for a server-side(host-side?) bug, one person using the Glass Stamina Vessel gives all players the blue Stamina outline.

I have written three of these reports and I still don't know how to do them properly.

**Comment by ScalarVector1** [comment]
most issues addressed in https://github.com/ProjectStarlight/StarlightRiver/pull/142, wall spawning issue was noted to not be reproducible. Will leave this open incase it comes up again.

**Comment by ScalarVector1** [comment]
Closing as no further reports of the remaining issue have been issued, assumed fixed
