### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dbstkddl** [ProjectStarlight/StarlightRiver#143]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: [what was supposed to happen?]
	Actual behavior: [what did happen?]
	Context: [what else happened around this? When did it happen?]
	Error message (if applicable): [what did the game think was wrong?]

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: [what mods you have loaded]
		Config settings: [the config settings for Starlight River]
		Game settings: [the settings for the game, things such as zoom, lighting mode, etc]
		Gameplay events happening: [whats going on? were you fighting a boss? mining ores? AFKing?]
		Your inputs: [what you did precisely to trigger the issue. EX: running to the left and using the thunderbuss to the right]
		OS: [what OS are you on?]

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

**Comment by ScalarVector1** [comment]
Closing this as it is just a blank issue format
