### ISSUE TITLE
Problem with Vitric Desert while creating world.

### ISSUE THREAD

**Issue by caseyesa** [ProjectStarlight/StarlightRiver#148]
![screeb](https://user-images.githubusercontent.com/98993225/152452426-5cb4e680-5607-4aa9-85a9-ce94a101a256.png)

**Comment by KobeDev09** [comment]
i have the same problem!

**Comment by KobeDev09** [comment]
![Terraria_ I just wanna know where the gold at_ 19_02_2022 11_10_53 pm](https://user-images.githubusercontent.com/83209717/154806738-58997972-a324-4183-a1b7-322b518e87d6.png)
