### ISSUE TITLE
Coach Gun Dynamite explosion time faster than expected

### ISSUE THREAD

**Issue by krazysamurai03** [ProjectStarlight/StarlightRiver#167]
## Issue Description
The Coach Gun Dynamite explodes a little under 2x faster than the description describes.
	Expected behavior: The dynamite will explode on its own after 5 seconds.
	Actual behavior: The dynamite explodes after about 2.7 seconds.
	Context: Just firing the gun normally, and I noticed it was exploding much faster than 5 seconds.
	Error message (if applicable): N/A

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Cheat Sheet, SLR
		Config settings: Default
		Game settings: 

[config.zip](https://github.com/ProjectStarlight/StarlightRiver/files/8373174/config.zip)

		Gameplay events happening: Just shooting the dynamite		
                Your inputs: Pressing right click
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

**Comment by ThatDamnPineapple** [comment]
Fixed in ce1d3cfb
