### ISSUE TITLE
Cloudstrike not firing in a typical manner

### ISSUE THREAD

**Issue by krazysamurai03** [ProjectStarlight/StarlightRiver#169]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
Cloudstrike will not fire unless dragged out of inventory and held.
	Expected behavior: Cloudstrike should function like other such weapons and fire from the hotbar normally
	Actual behavior: Will not fire unless dragged out of the inventory and held 
	Context: During normal gameplay with no special circumstances
	Error message (if applicable): N/A

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Cheat Sheet, SLR
		Config settings: Default
		Game settings: 
[config.zip](https://github.com/ProjectStarlight/StarlightRiver/files/8373360/config.zip)

		Gameplay events happening: Normal gameplay
		Your inputs: See linked video below
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
https://youtu.be/7xLeo-Q762U

**Comment by ThatDamnPineapple** [comment]
Fixed in b05c27b4
