### ISSUE TITLE
dual cross wrong damage

### ISSUE THREAD

**Issue by dottedboxguy** [ProjectStarlight/StarlightRiver#173]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: the arrow shot by the dual cross should have their damage somewhat infuenced by their arrow type
	Actual behavior: no matter what arrow was shot, the damage range didn't change at all
	Context: testing things with the dual cross
Github issues should match the following format, for ease of organization and readability.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: starlight river, HERO's mod
		Config settings: no change
		Game settings:  no change from bare settings
		Gameplay events happening: testing things with the dual cross on training dummies and enemies
		Your inputs: take dual cross, take 2 arrow stacks, shoot

log file was too new

**Comment by ThatDamnPineapple** [comment]
Fixed in f4b19b83
