### ISSUE TITLE
Crashlog. Drawing crash

### ISSUE THREAD

**Issue by davicslavic42** [ProjectStarlight/StarlightRiver#18]
With the newest build avialbe, I created a new world to use, later on I left the world to reload the modlist to add in cheatsheet then the game crashed. I expected the mod to reload fine since the world had no problems other than lag, but instead the game crashed and the logs listed an error dealing with drawing in the aurora biome. This error would appear whenever I tried to load or unload the mod unless I deleted any world created with the new build.

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/6987364/client.log)

**Comment by ScalarVector1** [comment]
This has been fixed and should no longer occur, this was caused by drawing logic attempting to run on the menu screen.
