### ISSUE TITLE
[Bug] Vitric Crystal textures are replaced with dirt.

### ISSUE THREAD

**Issue by CantWontDo** [ProjectStarlight/StarlightRiver#181]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Vitric crystals have their nice textures.
	Actual behavior: Looks like dirt.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River, Cheat Sheet, Hero's Mod
![image](https://user-images.githubusercontent.com/78101150/168401091-3d0e1988-f680-4e2e-8aba-92a97d3b6ee5.png)
![image](https://user-images.githubusercontent.com/78101150/168401097-4131dfbb-e507-4cc6-b3e0-4f7fd7e97889.png)
![image](https://user-images.githubusercontent.com/78101150/168401103-fc510a29-fb6a-40f9-adab-77085d4d0fe5.png)

## Additional context and log files
![image](https://user-images.githubusercontent.com/78101150/168401116-d9ee52ca-5e4c-4834-bb57-c67534f49b2b.png)

**Comment by ScalarVector1** [comment]
Fixed in https://github.com/ProjectStarlight/StarlightRiver/pull/288 upcoming
