### ISSUE TITLE
[Bug] Getting hit while grappling with Scrapshot permanently rotates player.

### ISSUE THREAD

**Issue by CantWontDo** [ProjectStarlight/StarlightRiver#182]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Player gets blasted back, rotating until normal.
	Actual behavior: Player gets blasted back, but is stuck at rotation of when it got hit.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River, Cheat Sheet, Hero's Mod
		![image](https://user-images.githubusercontent.com/78101150/168403556-ef3c5fa1-1bcc-47ff-9a7d-be0e5e27afaa.png)
		![image](https://user-images.githubusercontent.com/78101150/168403556-ef3c5fa1-1bcc-47ff-9a7d-be0e5e27afaa.png)
		![image](https://user-images.githubusercontent.com/78101150/168403572-3713b9cc-33e1-4834-b129-3a076c023881.png)
		Your inputs: Shoot hook with Scrapshot, fire and get hit at same time.
		OS: Windows 10

## Additional context and log files

https://user-images.githubusercontent.com/78101150/168403618-dbfd83e0-b03e-4c13-b1be-10f3cf293790.mp4

**Add any other context about the problem here.**

**Comment by CantWontDo** [comment]
Also, the vitric armor shards somehow got stacked in this clip? I will try and reproduce that.

**Comment by ScalarVector1** [comment]
Fixed in 38459d22850b20723d69f5908fef79eba041f391
