### ISSUE TITLE
Ceiros fight Final Stand

### ISSUE THREAD

**Issue by egshels** [ProjectStarlight/StarlightRiver#2]
At the end of the Ceiros fight, at 15% HP, he becomes invulnerable and charges up for a few seconds while covering himself in a crystal shield similar to the ones in his first phase. This time, the player can't break the shield as his crystals are all already broken. 
During this, the camera pans and zooms to a random segment of the arena where a magma orb has appeared, and then the magma comes together, creating a shield for the player to wield while a textbox from the Glassweaver appears stating that he's granting them some assistance along with some glowy loot effects around it. The player has to run to it and grab it, which makes them hold it out pointing towards their cursor. When they grab it, Ceiros flashes and his shield is completed, continuing the fight.

Ceiros summons several large orbiting shields of his own that block attacks unless shot between them. He then charges a and firing a huge magma beam over the course of 3 seconds. The player can block it with their shield, reflecting it and constantly pushing them back slightly. If they miss, and it hits them, they take very heavy damage. Reflecting a beam onto him does damage to his own shield if they aim it correctly between the gaps between his orbiting shields, which have much more health than his main shield. In expert mode, as his shield's health decreases, his orbitals rotate faster. During this entire phase, he cycles between firing off three magma beams and doing a few normal attacks. His shield is reformed, along with the players, after every string of normal attacks if it was broken. It takes 3 two full magma beams worth of reflection to break his shield. If the player kills him with the reflected beam, they gain the achievement "Sentinel, Shattered".

**Comment by ScalarVector1** [comment]
Closing this as this has been cut
