### ISSUE TITLE
Glassweaver lava cheese

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#21]
Filling Glassweaver's arena with lava will allow you to kill Glassweaver without doing anything. This is helped by you being able to leave Glassweaver's arena.

**Comment by ScalarVector1** [comment]
Nobuild zones have been patched to no longer allow buckets to be used within them. This willl be applied to the glassweaver arena once the structure is finished, so I am closing this issue for now.
