### ISSUE TITLE
[Bug] Chest inventories, including vanilla ones, don't draw or exist

### ISSUE THREAD

**Issue by ThatDamnPineapple** [ProjectStarlight/StarlightRiver#212]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Chests act as they do in vanilla
	Actual behavior: The chest inventory is invisible, and things can't be picked up from them.
	Context: It's recreatable. Restarting didn't fix it.
	Error message (if applicable): "Attempted to divide by zero"

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Cheatsheet, hero's mod, SLR
		Config settings: 
![image](https://user-images.githubusercontent.com/19764704/182037353-1b487b2f-ecc3-4c4f-993e-1ed88bd2246d.png)
![image](https://user-images.githubusercontent.com/19764704/182037363-795933cc-c050-42f2-80ab-ec973ce7c987.png)

		Game settings: 
![image](https://user-images.githubusercontent.com/19764704/182037396-9ba0ce5a-3dca-4a31-96c0-311eb477898b.png)
![image](https://user-images.githubusercontent.com/19764704/182037401-139e886f-9f23-4d0a-ad51-1df9a412c957.png)
![image](https://user-images.githubusercontent.com/19764704/182037432-f835e517-e3c9-446b-a32e-829def92cc21.png)

		Gameplay events happening:Testing the mod, flying around and using various items, I decided to check a chest, and this happened. Restarted twice, no fix.
		Your inputs:  Right clicked the chest to open it
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues an
d both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/9229339/client.log)

**Comment by ScalarVector1** [comment]
Have we been able to reproduce this at all?

**Comment by ScalarVector1** [comment]
Has not been reproduced in any way, assumed fixed or fluke
