### ISSUE TITLE
[Bug] Monk spade crashes the game

### ISSUE THREAD

**Issue by ThatDamnPineapple** [ProjectStarlight/StarlightRiver#221]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The monk spade is used like normal
	Actual behavior: The game crashes
	Context: I used the monk spade
	Error message (if applicable): See logs

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: SLR, cheatsheet, hero's mod
		Config settings: Doesn't matter
		Game settings: Doesn't matter
		Gameplay events happening: Was just messing with the mod.
		Your inputs: I left clicked with the monk spade from my inventory.
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/9283414/client.log)

**Comment by ScalarVector1** [comment]
fixed in https://github.com/ProjectStarlight/StarlightRiver/pull/294
