### ISSUE TITLE
[Bug] Worldgen usually crashes

### ISSUE THREAD

**Issue by ThatDamnPineapple** [ProjectStarlight/StarlightRiver#223]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The world generates as usual
	Actual behavior: The world very often fails.
	Context: Happens consistantly when creating a world. Different sizes, settings, restarting the game, tabbing out, none of it changes anything
	Error message (if applicable): ![image](https://user-images.githubusercontent.com/19764704/184001950-2a9fb78b-938f-4dad-8153-b1448bffe550.png)

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River, Cheatsheet, Hero's Mod, Crystilium (although it's happened with and without crystilium)
		Config settings: 
![image](https://user-images.githubusercontent.com/19764704/184002341-ef98a73c-90c7-46af-81da-33b43082319e.png)

		Game settings: 
![image](https://user-images.githubusercontent.com/19764704/184002167-9c4da749-5864-446a-a093-b7067df3cfcc.png)
![image](https://user-images.githubusercontent.com/19764704/184002208-7ac5ab27-a6b6-4baa-becc-3299db99ac0e.png)
![image](https://user-images.githubusercontent.com/19764704/184002243-dae74a41-3642-4f05-a868-83ab1de59217.png)

		Gameplay events happening:  Happens consistantly when creating a world. Different sizes, settings, restarting the game, tabbing out, none of it changes anything
		Your inputs: See above
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/9303374/client.log)

**Comment by ScalarVector1** [comment]
fixed in https://github.com/ProjectStarlight/StarlightRiver/pull/321
