### ISSUE TITLE
[Bug] Rainbow Cycle Dye causes a game crash when applied

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#227]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Dye does something
	Actual behavior: Game crashed
	Context: Dye was applied to Steampunk Goggles

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: SLR, Cheat Sheet 0.7.3.4, Hero's Mod 0.4.8
		Config settings: Default settings
		Game settings: [config.json.txt](https://github.com/ProjectStarlight/StarlightRiver/files/9364245/config.json.txt)
		Gameplay events happening: Hero's Mod menu and chest inventory menu were open
		Your inputs: Dragged from Hero's Mod menu into the head dye slot
		OS: Windows 10 Pro x64

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/9364216/client.log)

**Comment by ScalarVector1** [comment]
Can this be reproduced on a vanilla tModLoader installation?

**Comment by ScalarVector1** [comment]
Can no longer be reproduced
