### ISSUE TITLE
Main menu background resolution issues[Minor Bug]

### ISSUE THREAD

**Issue by FloromacobaJ** [ProjectStarlight/StarlightRiver#246]
When changing the tmodloader background to the Starlight river one, the image isn't placed properly.
I only have SLR mod installed.
It seems like the SLR one is placed over the base game one, and it doesn't scale as it should deppending on the screen resolution, so the vanilla one peeks out. 
Here is the comparison between 3840x2160 with 1920x1080:
![1920x1080](https://user-images.githubusercontent.com/99040080/187744228-47e175cc-0e4a-41db-87ad-1fafe831f713.png)

![3840x2160](https://user-images.githubusercontent.com/99040080/187744621-bf3da4fe-91a5-4a24-90bf-c0f4ffc7b910.png)

**Comment by ScalarVector1** [comment]
Fixed in 0afcd7ac2971ccefb6d05b0d621d060d2bc8dcf2
