### ISSUE TITLE
Game crashes upon entering the Auroracle arena

### ISSUE THREAD

**Issue by egshels** [ProjectStarlight/StarlightRiver#25]
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7263054/client.log)

**Comment by ScalarVector1** [comment]
Appears to be related to @SuperAndyHero 's alternative method for drawing lit sprites? Cannot gleam any more from the logs without repro steps. Please include repro steps in your crash and bug reports :)

**Comment by egshels** [comment]
repo steps: enter auroracle arena

**Comment by ScalarVector1** [comment]
Can you please also share the mod config that you were using when you encountered this?

**Comment by egshels** [comment]
Lighting poll rate is set to 10 and special particles are enabled

**Comment by ScalarVector1** [comment]
Closing this as it is ancient and no longer is reproducable
