### ISSUE TITLE
[Bug] Ignition Gauntlets Hardlock/Crash

### ISSUE THREAD

**Issue by Aetheriant** [ProjectStarlight/StarlightRiver#253]
## Issue Description
	Expected behavior: Ignition Gauntlets M1 Barrage
	Actual behavior: Character locks up, all menus break, game is bricked and user needs to end process.
	Context: Punching with the M1 attack of ignition gauntlets while flying erratically. I was hovering with Celestial Starboard at the 
        time, but Atasi was using regular wings.

## Reproduction
		Mod list: Starlight River Snoobel master branch posted in test-builds, Cheat Sheet, Cheat Extensions
		Config settings: Unchanged
		Game settings: Unchanged
		Gameplay events happening: Punching slimes with ignition gauntlets
		Your inputs: A+S+Space while punching with the gauntlets.
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/9480234/client.log)

After messing with it more in VC with other testers, seems to happen when holding multiple movement inputs while doing either attack on the gauntlets. Textures404 managed to crash the game by holding multiple inputs and doing the M2 attack.

**Comment by ScalarVector1** [comment]
Fixed in f964941eb3d53ce3dd02f0e666b1e918219ac3ef
