### ISSUE TITLE
[Bug] Auroracle doesnt follow the player to the edges of its arena

### ISSUE THREAD

**Issue by Textures404** [ProjectStarlight/StarlightRiver#256]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Auroracle follows player in bottom chamber of boss room before boss fight
	Actual behavior: Upon the player reaching the edges of the room, auroracle stops moving abruptly
	Context: Was flying around auroracle's boss fight room while it is still behind the glass, it stops moving when you go past the furthest right or left window at the bottom.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River, Hero's Mod
		Config settings: Nothing changed from default
		Game settings: zoom 100%, lighting color, autosave on, autopause off, lighting color, quality auto, background on
		Gameplay events happening: When reaching the edge of auroracle's boss fight room (past the furthest left or right window), auroracle stops moving behind the glass abruptly and just sits there
		Your inputs: Nothing specific, just movement keys and reaching one edge of the arena before auroracle
		OS: Windows 11

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

**Comment by ScalarVector1** [comment]
Fixed in 718eb92be74be6e8d24993e6927e2fba90dc91bb
