### ISSUE TITLE
Breacher chestplace becomes invisible while jumping [Minor Bug]

### ISSUE THREAD

**Issue by Textures404** [ProjectStarlight/StarlightRiver#262]
## Issue Description
A thorough description of the problem, including:
    Expected behavior: Breacher chestplate remains visible while jumping
    Actual behavior: While jumping or falling, the sprite for the breacher chestplate on they player dissapears, leaving the sprite for the bare chest
    Mod list: Starlight River, Hero's Mod
    Reproduction: Jump or fall while wearing the breacher chestplate

**Comment by ScalarVector1** [comment]
This is due to missing assets for the updated 1.4 spritesheet. As this is entirely an art issue, I will be closing this ticket.
