### ISSUE TITLE
[Minor Bug] Pyroclastic Flow doesn't fire from inventory

### ISSUE THREAD

**Issue by JudeEgg** [ProjectStarlight/StarlightRiver#265]
## Pyroclastic Flow has issues firing from inventory upon obtaining it
Most weapons can be used straight from the inventory however pyroclastic flow will not fire from the inventory until AFTER held and used in hotbar. I was using heros mod and cheat sheet along with Starlight River when this issue happened and I took pyroclastic flow from the heros mod item browser. Saving and exiting allowed me to recreate this issue. Video attached shows the issue

https://user-images.githubusercontent.com/112596134/189463998-0b412c01-1181-4b79-9630-bb8d32e25a7a.mp4

**Comment by ScalarVector1** [comment]
No longer reproducable
