### ISSUE TITLE
[Minor Bug] Cloudstrike duplicates its audio and visuals when held on cursor instead of in inventory.

### ISSUE THREAD

**Issue by Aetheriant** [ProjectStarlight/StarlightRiver#266]
## Issue Description
A thorough description of the problem, including:
    Expected behavior: Cloudstrike visuals and audio play as normal when shot/held from the mouse cursor instead of from a hotbar slot.
    Actual behavior: Cloudstrike duplicates its visuals and audio when shot/held from the mouse cursor instead of from a hotbar slot.
    Mod list: SLR, Cheat Sheet, Lights and Shadow
    Reproduction: Click Cloudstrike in your inventory to grab it with your cursor, click anywhere to fire it, hurt your ears :(

**Comment by ScalarVector1** [comment]
No longer reproducable
