### ISSUE TITLE
[Bug] Crash occasionally occurs for seemingly no reason when opening map screen

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#272]
## Issue Description
	Expected behavior: Map screen opens, no crash
	Actual behavior: Game crash
	Context: In underground desert searching for artifacts.  
	Error message (if applicable): System.InvalidOperationException: Texture2D creation failed! Error Code: Not enough memory resources are available to complete this operation. (0x8007000E)

## Reproduction
		Mod list: SLR, Fargo's Mutant Mod, Cheat Sheet, Hero's Mod
		Config settings: Default settings
		Game settings: See attached config file
		Gameplay events happening: Mining for artifacts
		Your inputs: Opened map screen

## Additional context and log files
**Add any other context about the problem here.** 
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/9542667/client.log)
[config.json.txt](https://github.com/ProjectStarlight/StarlightRiver/files/9542668/config.json.txt)

**Comment by MemeHoovy** [comment]
it literally means your PC is running out of memory .__.

**Comment by ScalarVector1** [comment]
This should be fixed with the ScreenTarget system now being memory safe
