### ISSUE TITLE
not being able to dash upward

### ISSUE THREAD

**Issue by dottedboxguy** [ProjectStarlight/StarlightRiver#30]
i'm gonna put some context for this : i am left handed, so i remap all my controls to work with oklm (right side of a french keyboard ).
this is pretty straightforward : i can dash in every direction except upward, that may be caused by the up dashing function not actually being tied up with the player remapped controls

**Comment by ScalarVector1** [comment]
Cannot reproduce this by only rebinding upwards movement to O or any other key. Unfortunately I do not have a french keyboard to test with the specified hardware. Any additional context to reproducing this issue and logs would be greatly appreciated.
