### ISSUE TITLE
little vibrant crystals seems pretty janky

### ISSUE THREAD

**Issue by dottedboxguy** [ProjectStarlight/StarlightRiver#31]
i saw 3 issues with the little vibrant crystal : 
1 : they generate between each other, cutting some of them in half (i have visual proof)
2 : they don't break when you break the ground under them
3, pretty minor but still : the vibrant aura arround it is slightly offcentered upward (exactly 2 pixels upward)

**Comment by ScalarVector1** [comment]
Hopefully fixed in 8784c6c352fa9009b68bf40bb8b849d3c557dbd6 and f12441e6839e789ab73a10e092dfb82218afaf33, please test worldgen again when tonights build releases

**Comment by ScalarVector1** [comment]
Confirmed to no longer occur
