### ISSUE TITLE
[Minor Bug] Strange Twisted Greatsword + Feral Claws interaction

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#329]
## Issue Description
A thorough description of the problem, including:
    Expected behavior: No change to Twisted Greatsword behavior
    Actual behavior: Multiple Twisted Greatsword projectiles (at least I think they're projectiles?) are created, causing the weapon to hit at a much higher speed and causing a large DPS increase. Basically turns the weapon into a buzzsaw. Also creates a lot of particles.
    Mod list: SLR, Fargo's Mutant Mod, Hero's Mod, Cheat Sheet (all on latest version)
    Reproduction: Equip Feral Claws, or an upgrade, and use Twisted Greatsword

**Comment by TripleFate** [comment]
fixed in #330
