### ISSUE TITLE
The visual of the Spore Sac crashes the game

### ISSUE THREAD

**Issue by Waasephi** [ProjectStarlight/StarlightRiver#36]
## Issue Description
When going through my character list, I scrolled through and my game suddenly crashed.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: I had SLR, Cheatsheet and Hero's Mod, and Worldgen Previewer enabled
		Config settings: ![image](https://user-images.githubusercontent.com/34556008/137177814-c2a2b835-61a9-41c0-ab8c-fd5cb903d343.png)
		Gameplay events happening: Looking through character list
		Your inputs: Looked at a character that had the visual of a Spore Sac enabled
		OS: ![image](https://user-images.githubusercontent.com/34556008/137178165-45fd41cf-3a5a-438d-bb1b-bad1eb9e53cf.png)

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7340044/client.log)

**Comment by ScalarVector1** [comment]
Should be fixed in 374d10fb5fe540343af1172a98096ef911b32c87
