### ISSUE TITLE
[Bug] - When using the pyroclastic flow in Auroracle's arena, you cant shoot anything past the top part of the arena 

### ISSUE THREAD

**Issue by Lemmy-Koopa** [ProjectStarlight/StarlightRiver#363]
for some reason it only gets stuck on that part of the arena. Everywhere else in the arena works fine. 
![SlrBugTest #1](https://user-images.githubusercontent.com/56778754/229363264-21b38b20-ff6b-4482-b7ff-6fd28d89f824.gif)

**Comment by ScalarVector1** [comment]
Fixed in fb78979
