### ISSUE TITLE
[Bug] Starwood Boomerang Disappears when holding left click 

### ISSUE THREAD

**Issue by Lemmy-Koopa** [ProjectStarlight/StarlightRiver#367]
When holding down the left click, the boomerang just disappears as shown in the gif.

![SlrBugTest #2](https://user-images.githubusercontent.com/56778754/229406329-e515c4f7-6ccf-4006-8c6d-a86b687cfd0c.gif)

**Comment by ScalarVector1** [comment]
fixed in  87df6c2c7926e019f44ba7e06ab4f44627d60c28
