### ISSUE TITLE
If you join a world/character that you have previously had the build enabled on without it, it crashes the game

### ISSUE THREAD

**Issue by Waasephi** [ProjectStarlight/StarlightRiver#37]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
I tried to load a character to remove a crashing accessory and even with the mod disabled the game still crashes.
![image](https://user-images.githubusercontent.com/34556008/137179374-034539cc-689c-4518-a905-e48688a80105.png)

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Hero's Mod, Cheat Sheet, Worldgen Previewer, SLR had been enabled on the character just before but was removed.
I joined a world that I had previously used the demo build on both the character and the world, which crashed the game when it was disabled.

## Additional context and log files
**Add any other context about the problem here.** 
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7340096/client.log)

**Comment by ScalarVector1** [comment]
Going to consider this fixed since its not been able to be reproduced
