### ISSUE TITLE
[Bug] - Twisted Greatsword Projectile Disappears when using Forbidden Winds   

### ISSUE THREAD

**Issue by Lemmy-Koopa** [ProjectStarlight/StarlightRiver#370]
Not the best job showing it in this gif but when using the ability the projectile disappears but the properties are still there.

![SlrBugTest #6](https://user-images.githubusercontent.com/56778754/229412229-c1b22205-1109-45ba-89c2-ce90e05df84f.gif)

**Comment by ScalarVector1** [comment]
fixed in a4d3e2ccb36502c5472b547d5dcfc07dbc9cb8e2
