### ISSUE TITLE
Moonstone Set Info not Appearing

### ISSUE THREAD

**Issue by Lampshaede** [ProjectStarlight/StarlightRiver#38]
## Moonstone Set Bonus [hold up] active (hold up for datsuzei stats) doesn't work
**A thorough description of the problem, including:**
	Expected behavior: Stats appear
	Actual behavior: nothing
	Context: replicable by simply equipping the armour and holding up as suggested

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Recipe Browser, Cheat Sheet, Starlight River
		Config settings: the default config settings for Starlight River
		Terraria Settings: **Autopause on**, 1980x1020, borderless windowed,  else default
		Gameplay events happening: hitting dummies to test set bonus
		Your inputs: hold up
		OS: Windows 10

**Comment by ScalarVector1** [comment]
This is an issue which is unfortunately outside of our scope. This is an existing vanilla issue where tooltips do not update when autopause is enabled.
