### ISSUE TITLE
[Minor Bug] Giant crystals from virtic desert sometime spawn in the temple but temple overrides it

### ISSUE THREAD

**Issue by Lucas01E621** [ProjectStarlight/StarlightRiver#388]
## Issue Description
A thorough description of the problem, including:
    Expected behavior: Crystal should spawn on sands
    Actual behavior: sometimes crystals spawn on temple
    Mod list: Starlight River only
    Reproduction: I encountered this by chance but I think generating world would reproduce the bug

**Comment by ScalarVector1** [comment]
This should have been fixed in a previous version so closing for now.
