### ISSUE TITLE
Datsuzei Background Overrides Darkness

### ISSUE THREAD

**Issue by Lampshaede** [ProjectStarlight/StarlightRiver#39]
## Datsuzei Hotbar Overrides Darkness
**A thorough description of the problem, including:**
	Expected behavior: Datsuzei changes hotbar
	Actual behavior: Datsuzei hotbar turns blocker background invisible
	Context: Using Datsuzei there's a window around that penetrates the darkness

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Recipe Browser, Cheat Sheet, Starlight River
		Config settings: The default Starlight River config
		Game settings: Autopause on, 1980x1020, borderless windowed, else default (zoom 100, ui 100)
		Gameplay events happening: using datsuzei in tutorial background area
		Your inputs: Double tap down after moonstone set charged while in 'tutorial' background
		OS: Windows 10

## Additional context and log files
![image](https://user-images.githubusercontent.com/33045275/137183434-d162d4fa-a545-425b-9009-c057ce0f24d1.png)

**Comment by BlindSE** [comment]
Same issue as #40 
merge pls.
