### ISSUE TITLE
[Bug] [1.4.4] Main Engine Crash when Loading Mod List

### ISSUE THREAD

**Issue by Setnour6** [ProjectStarlight/StarlightRiver#391]
This bug affects gameplay as a player.

## Issue Description

Going to the "Workshop Hub" and then to "Manage Mods" crashes the game.

Expected behavior: The Mods List opens up normally and shows the list of mods enabled and disabled.
Actual Behavior: The Mods List opens up but doesn't show the list of mods, and the game crashes immediately.

Crash Error Message:
![image](https://user-images.githubusercontent.com/70764728/235461015-c7a47e5e-628c-4b61-b18a-298b1f273a27.png)
I can't resize the tab or close it normally. I have to close it through the taskbar.

Console Error Message:
![image](https://user-images.githubusercontent.com/70764728/235461131-bebd8a88-9b32-4219-9b9d-a165e68571a1.png)

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: HERO's Mod, Cheat Sheet, DragonLens, UwUMod (self-compiled) (does nothing special), Super Dummy From Fargo's Mod (private mod, self-compiled), Example Mod.
		Config settings: Mostly Default, but stamina is set to show when regening, labels (debug, etc) set to "both".
		Game settings: Zoom is normal, lighting mode is Color. I use windowed mode.
		Gameplay events happening: Accessing mod list.
		Your inputs: I moved my mouse during loading, but even without moving my mouse, it still happens.
		OS: Windows 11

Step 1. In main menu, click on "Workshop".
Step 2. Click on "Manage Mods".
Step 3. See what happens.

## Additional context and log files

Temporary workaround is to go to "Documents\My Games\Terraria\tModLoader-preview (or tModLoader if you are not on preview) \Mods" and change "enabled.json" to remove StarlightRiver from the file. After that, you can open tModLoader again.
Client Log: [client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11365669/client.log)

**Comment by ScalarVector1** [comment]
I cant seem to reproduce this issue, can you give more context to the reproduction?
