### ISSUE TITLE
[Bug] Whirlwind pickaxe causes player to sprint indefinitely

### ISSUE THREAD

**Issue by CantWontDo** [ProjectStarlight/StarlightRiver#394]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The whirlwind pickaxe causes the player to dash when right click is released at full charge.
	Actual behavior: The player sprints in one direction faster than normal until right click is released, then dashes.
	Context: I clicked right click immediately after letting go of right mouse button at full charge.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: DragonLens, Starlight River
		Config settings: 
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/09cc7d44-ee6d-4dbf-a1b1-aea00e8c1dc8)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/a7f15547-ae70-4520-aa0c-e9bc00877f40)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/796dc6d2-8b11-4f2e-8bc1-a6b0d23840d8)

		Game settings:
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/8e9c8b14-b2c8-4767-83b1-bb91e00a23f1)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/4e8373f3-43d6-4e48-9f39-ec096f1c2318)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/b6ea0bbc-4233-4ec4-b572-c5d64cb3617c)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/5f25c246-92ea-467b-aaf5-05d3ea6d47c6)

		Gameplay events happening: I was activating the ability of the whirlwind pickaxe.
		Your inputs: Charge whirlwind pickaxe to full. Release right mouse button. Immediately press it again.
		OS: Windows 10

## Additional context and log files

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11619309/client.log)

https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/c3ad9fe8-d342-4520-8176-dfff8021694e

**Comment by CantWontDo** [comment]
It also allows me to do this 

https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/9ff8075b-ee3d-4f57-81d8-80fbe2f51a60

**Comment by CantWontDo** [comment]
https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/362e94ca-7920-47a1-90e2-e6dd62cb1d8c

Charge also persists after death.

**Comment by ScalarVector1** [comment]
Should be resolved (and nerfed)
