### ISSUE TITLE
[Minor Bug]Exotic Geode is marked as consumable but does not do anything.

### ISSUE THREAD

**Issue by CantWontDo** [ProjectStarlight/StarlightRiver#395]
## Issue Description
A thorough description of the problem, including:
    Expected behavior: Exotic Geode does something when you use it.
    Actual behavior: Nothing happens, the item is not used
    Mod list: DragonLens, Starlight River

**Comment by SkippZzMods** [comment]
Pretty sure you use it at an extractinator
