### ISSUE TITLE
[Minor Bug] Glass case found in houses is destroyable with pickaxe.

### ISSUE THREAD

**Issue by CantWontDo** [ProjectStarlight/StarlightRiver#396]
## Issue Description
A thorough description of the problem, including:
    Expected behavior: Glass case is destroyed with forbidden winds, indestructible otherwise. 
    Actual behavior: I destroyed the glass case with whirlwind pickaxe.
    Mod list: DragonLens, Starlight River

**Comment by ScalarVector1** [comment]
Should be resolved
