### ISSUE TITLE
[Bug] Music (and sfx?) do not play during Shrine of Evasion

### ISSUE THREAD

**Issue by CantWontDo** [ProjectStarlight/StarlightRiver#399]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The shrine of evasion music plays when it is active.
	Actual behavior: The shrine of evasion music did not play, and was occasionally overridden by the shimmer music.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: DragonLens, Starlight River
		Config settings: 
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/09cc7d44-ee6d-4dbf-a1b1-aea00e8c1dc8)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/a7f15547-ae70-4520-aa0c-e9bc00877f40)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/796dc6d2-8b11-4f2e-8bc1-a6b0d23840d8)

		Game settings:
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/8e9c8b14-b2c8-4767-83b1-bb91e00a23f1)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/4e8373f3-43d6-4e48-9f39-ec096f1c2318)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/b6ea0bbc-4233-4ec4-b572-c5d64cb3617c)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/5f25c246-92ea-467b-aaf5-05d3ea6d47c6)

		Gameplay events happening: Activate shrine of wit.
		Your inputs: Right click shrine of wit.
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/771b7a81-4c1f-4d33-a86c-af24b7716bde
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11619717/client.log)

**Comment by ScalarVector1** [comment]
fixed
