### ISSUE TITLE
Datsuzei UI conflicts with the indoor overlay shader

### ISSUE THREAD

**Issue by BlindSE** [ProjectStarlight/StarlightRiver#40]
## Issue Description
**Expected behavior:** N/A

**Actual behavior:** UI conflicts with the black overlay that obstructs your view while inside the temple, causing the area around the weapon UI showing what was previously supposed to be obscured by the shader.

**Context:** Happens any time you toggle the set bonus ability of the moonstone armor inside the temple.

**Error message (if applicable):** N/A

## Reproduction
**Mod list:** SLR, Hero's Mod, Cheat Sheet

**Config settings:** Deafult

**Game settings:** Deafult

**Gameplay events happening**: Player simply exists 

**Your inputs:** Double tap down

**OS:** Win 10 VM running under Arch with GPU passthrough

## Additional context and log files

UI Screenshot
![Image](https://i.imgur.com/5xszmqi.png)

*You guys should really slim down your bug report template, just sayin.*

**Comment by ScalarVector1** [comment]
Fixed in 4bacb538b42cf0f466abdc2b16219c2f4f32c196
