### ISSUE TITLE
[Minor Bug] Snake enemy can teleport to corners of blocks

### ISSUE THREAD

**Issue by CantWontDo** [ProjectStarlight/StarlightRiver#402]
## Issue Description
A thorough description of the problem, including:
    Expected behavior: Vitric snake enemy can only teleport onto blocks.
    Actual behavior: Vitric snake can and mostly does teleport to the corners of blocks, making it look like it is floating. It also frequently falls out of the air.
    Mod list: Starlight River, DragonLens
    Reproduction: Spawn a vitric snake enemy and wait for a bit.
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/c3980dda-e437-456e-876f-c566f68dbd58)

**Comment by CantWontDo** [comment]
https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/8b4fc39e-ad76-4390-9588-65c2f232889c

Video example

**Comment by ScalarVector1** [comment]
fixed
