### ISSUE TITLE
Missing credit

### ISSUE THREAD

**Issue by TripleFate** [ProjectStarlight/StarlightRiver#414]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: TripleFate showing up in the special thanks to our developers on steam workshop
	Actual behavior: Name not there
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/93957884/0e99491a-516f-485b-9cfc-312d66019651)

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Navigate to steam workshop and read the special thanks section
https://steamcommunity.com/sharedfiles/filedetails/?id=2984622072

**Comment by SkippZzMods** [comment]
INFUCKING SANE LMFAOOOO

**Comment by steviegt6** [comment]
add tomat

**Comment by ScalarVector1** [comment]
No longer applicable
