### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SMPLtxt** [ProjectStarlight/StarlightRiver#416]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Functioning interaction
	Actual behavior: tools are unusable and holding left click freezes character without placing/using
	Context: playing the game

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River
		Config settings: Default
		Game settings: default
		Gameplay events happening: on a server i hosted for me and 2 others
		Your inputs: hosting game
		OS: windows 11, windows 10

## Additional context and log files
**Add any other context about the problem here.** 
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11644574/client.log)
[server.log](https://github.com/ProjectStarlight/StarlightRiver/files/11644575/server.log)

Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

**Comment by Biverom** [comment]
Multiplayer is not supported yet. Is this bug working in singleplayer?
