### ISSUE TITLE
scrapshot grapple not working as intended when the snek enemy teleports mid-grapple

### ISSUE THREAD

**Issue by krazysamurai03** [ProjectStarlight/StarlightRiver#42]
## Issue Description
	Expected behavior: If a grappled Snek were to teleport, I would expect the grapple to break.
	Actual behavior: The player is dragged to the top of the map by the Snek.
	Context: I was grappling Sneks with the Scrapshot, and suddenly I was on top of the map.
	Error message (if applicable): The first time this happened I was given a System.OutOfMemoryException, however on subsequent attempts to reproduce the game did not crash.

## Reproduction
		Mod list: Starlight River
		Config settings: No custom mod config.
		Game settings: All settings default with the exception of custom keybinds and volume.
		Gameplay events happening: Fighting a Snek with the Scrapshot and a set of Breacher armor.
		Your inputs: All you need to do to recreate this is to time the grapple of the Scrapshot so that the Snek teleports before you reach it.
		OS: Windows 10 Pro 64 bit

## Additional context and log files
**[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7341039/client.log)**

**Comment by ScalarVector1** [comment]
Potentially fixed in d3926eff60236ec1ff6a15033764592606880b1e, please test again after tonights build drops

**Comment by ScalarVector1** [comment]
Confirmed to no longer occur
