### ISSUE TITLE
Animations not showing in multiplayer [Bug]

### ISSUE THREAD

**Issue by Brewlink1** [ProjectStarlight/StarlightRiver#420]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Animations appearing for other players
	Actual behavior: Animations did not appear for other players 
	Context: while using point of light or the whirlwind pickaxes ability and laser pointers the animations would not show up
	
## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: just starlight river
		Config settings: default
		Game settings: default
		Your inputs: using the items in general

**Comment by ScalarVector1** [comment]
This is far too general to really be actionable unfortunately, going to have to close this
