### ISSUE TITLE
crow NPC stuck in introduction [Bug]

### ISSUE THREAD

**Issue by Billybobthort** [ProjectStarlight/StarlightRiver#422]
I have just defeated the squid boss and got the message a new NPC was arriving so I went back to spawn and crow guy spawned in and I've been stuck in his dialogue. even if I try to save and exit the same dialogue still pops up with another continue button (as shown in picture) also I don't know if this matters but I have other mods installed and when I try to talk to him it says that the Modder forgot to give chat message
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/131192232/3c75a691-1c56-4220-8c02-76382d091fc2)

**Comment by miniwoof** [comment]
this happened to me but i only have starlight river installed and does it to all npcs

**Comment by Billybobthort** [comment]
the solution that has worked for me is to change my UI scale in settings to 100.
