### ISSUE TITLE
[Major Bug] Cant interact with the NPC and it keeps adding "Continue" Buttons and there is no way out of it.

### ISSUE THREAD

**Issue by ShadyKang** [ProjectStarlight/StarlightRiver#423]
I tried to press every button, restart the quit and rejoin the world, and restart tmodloader and nothing had worked...

![Terraria_ Better than life 6_3_2023 10_33_47 PM](https://github.com/ProjectStarlight/StarlightRiver/assets/135484913/c68838b3-2b51-4db5-a863-a1649093b94b)

![Terraria_ Small Blocks, Not for Children Under the Age of 5 6_3_2023 10_47_47 PM](https://github.com/ProjectStarlight/StarlightRiver/assets/135484913/3aa3253b-958f-44e9-bb39-ea6dbcb2afe5)

I have already seen multiple people giving bug reports about this issue and it's preventing many people from playing.

**Comment by Heterotardigrade** [comment]
Having the same Issue!

**Comment by Spamhash** [comment]
yup, same here

**Comment by Heterotardigrade** [comment]
Make sure zoom and ui scale are set to 100%. That fixed it for me.

**Comment by ScalarVector1** [comment]
This should have been fixed in a previous version so closing for now.
