### ISSUE TITLE
[Minor Bug] i got a debug item

### ISSUE THREAD

**Issue by ruhyk** [ProjectStarlight/StarlightRiver#425]
i wanted to break some blocks near a combat shrine barrier while it was inactive 
for some reason it also destroyed the barrier and dropped the block
Reproduction: use a dynamite near a combat shrine wall while inactive (i don't know if it works while active) it will destroyed the 
invisible barrier and it will give the block called combatshrinebarrierblock it may also work with normal bombs but i didn't test
Mod list: starlight river

![the block](https://github.com/ProjectStarlight/StarlightRiver/assets/135485174/a4f4efe7-f162-48c0-bd0d-20cfe0e021cf)

**Comment by ScalarVector1** [comment]
Should be fixed in upcoming patch
