### ISSUE TITLE
Barrier aura is offset when zooming in

### ISSUE THREAD

**Issue by EmanuelOR127** [ProjectStarlight/StarlightRiver#428]
Expected behavior: The Barrier's aura should follow the shape, size and position of the player at all zoom levels.
    Actual behavior: The Barrier's aura is bigger than the actual player and offsets when zoom is greather than 100%.
    Mod list: Starlight River
    Reproduction: Always
![Bug Picture](https://github.com/ProjectStarlight/StarlightRiver/assets/130308194/3bf9e95e-519f-4794-95a5-fcf7d1a3ecc3)

**Comment by ScalarVector1** [comment]
This should have been fixed in a previous version. Closing for now.
