### ISSUE TITLE
[Bug] Crash when using the Gravebuster

### ISSUE THREAD

**Issue by DannnDoesArt** [ProjectStarlight/StarlightRiver#429]
I died 2 times and had two monoliths (i believe thats what their called) down, and upon using the item the character did not pull the item out and the game froze for a bit, until it just closed on me with no error message

  The only mods that i have enabled are SLR although, i had the Optimizerarria (https://steamcommunity.com/sharedfiles/filedetails/?id=2447428824) and FPS Booster (https://steamcommunity.com/sharedfiles/filedetails/?id=2692462799) resource packs, as my computer can barely run tmod, every config (including mod configs) set to the lowest possible except for the screenshake and the lighting poll rate, lighting set on Retro, with the Task Manager priority set to the high and affinity on driver 0 disabled, on Win 10

  And here is the log i could find, not sure its the right one but hope this helps somehow!

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11644698/client.log)

**Comment by ScalarVector1** [comment]
Log does not indicate a crash, and this cannot be reproduced. Closing for now.
