### ISSUE TITLE
Starlight River failed to unload

### ISSUE THREAD

**Issue by TheSkerch** [ProjectStarlight/StarlightRiver#433]
## Issue Description
	Expected behavior: it was supposed to unload the mod, as a part of the mod loading process
	Actual behavior: the game failed to unload the mod and gave me an error screen
	Context: I tried to reload my mods with starlight river enabled
	Error message: "One or more errors occurred while unloading and tModLoader must be restarted to prevent further issues.
        StarlightRiver was unable to unload properly. Modders must use defensive programming to ensure unloading completes 
        regardless of any errors during unloading."

## Reproduction
		Mod list: Starlight River.
		Config settings: default
		Game settings: its not an issue that could be influenced by those kind of settings
		Gameplay events happening: trying to reload my mods with the mod enabled
		Your inputs: reloaded my mods
		OS: windows

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11644885/client.log)

**Comment by MustardManExtreme** [comment]
Turns out this was an issue with the build of tmodloader i was on, the 2023.06.8 one works fine so try that if ur still encountering the issue
