### ISSUE TITLE
[Demo Bug] World Failed To Load

### ISSUE THREAD

**Issue by Heterotardigrade** [ProjectStarlight/StarlightRiver#435]
Expected behavior: Tried to load into my save.
	Actual behavior: World wouldn't load.
	Context: Exited and saved, then tried to enable boss checklist. After getting a message that boss checklist didnt work, I tried to return to my save.
	Error message (if applicable): "Load failed! No backup found"

		Mod list: Basic Automated Mining v1.2.0, Starlight River.
		Config settings: Default.
		OS: Windows 10
![stinky load fail moment](https://github.com/ProjectStarlight/StarlightRiver/assets/135508211/a13b5e79-85ff-4b69-9474-9fda3f18f26c)

**Comment by ScalarVector1** [comment]
Closing as no repro steps or log, thus cannot do much to investigate this
