### ISSUE TITLE
[Minor Bug]

### ISSUE THREAD

**Issue by Heterotardigrade** [ProjectStarlight/StarlightRiver#436]
Bug: After jumping out of the rainbow water, my character was tilted roughly 30 degrees. When I jumped back into the water then back out again, it was fixed.

    Mod list: Basic Automated Mining v1.2.0
    Reproduction: Can't get it to happen again
![starlightriverbug](https://github.com/ProjectStarlight/StarlightRiver/assets/135508211/91849ab9-86b3-41e8-8513-33105b4838d1)

**Comment by ScalarVector1** [comment]
Duplicate
