### ISSUE TITLE
Crow NPC dialogue text that should never be seen

### ISSUE THREAD

**Issue by Isamel69** [ProjectStarlight/StarlightRiver#438]
## Issue Description
	Expected behavior: Ending the conversation with the crow npc
	Actual behavior: Can't end the conversation, every time I press accept or continue a new dialogue box appears that says that shouldn't had happened. Making it impossible to continue playing
	Context: Was my first time talking to the crow npc, started the conversation like normal but towards the end of the conversation I got the error text box

## Reproduction
		Mod list: Starlight River
		Config settings: Default settings
		Game settings: zoom to 100% UI 100%, lighting mode: color
		Gameplay events happening: Lantern Night
		Your inputs: Was in the snow biome doing some mining and suddenly a message appears that a strange man wanted to talk to me in my spawn point. I teleported back to base and met the crow npc, and Initially I couldn't talk to him so I exited the game and then got back to try and talk to him again. Changed my UI settings to 100% and started the dialogue like normal but towards the end of the dialogue I got the error text box. Trying to press continue or accept to the end of the conversation results in him repeatedly saying that the text box should had never be seen.
		OS: Windows

## Additional context and log files

![Screenshot 2023-06-04 061709](https://github.com/ProjectStarlight/StarlightRiver/assets/76609863/36fd4d9f-b0df-41f0-97f7-f1bd6b1933d3)

**Comment by Isamel69** [comment]
I now restarted my game and got to talk to him again, his dialogue restarted and I got to end the conversation how it was supposed to be, but my response options were bugged and had 4 "continue" options, 3 of them send me to the error text box and 1 of them was the actual "real" one.

**Comment by ScalarVector1** [comment]
Going to close this as I believe this should have been fixed previously
