### ISSUE TITLE
[Bug]aurora bricks are bomb-able

### ISSUE THREAD

**Issue by Lion8cake** [ProjectStarlight/StarlightRiver#439]
Github issues should match the following format, for ease of organization and readability.
	Expected behavior: Aurora bricks should not be bomb-able
	Actual behavior: Currently the bricks can b destroyed by bombs which both includes the walls and the tiles causing breackage with the strcuture wall and illusion of the arena
	Context: I accidentally threw a bomb in the arena

		Mod list: Starlight river, dragonlens, worldgen previewer
		Config settings: normal (haven't touched the configs yet)
		Gameplay events happening: in the aurora arena
		
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/69915693/0093511e-9183-4c78-802c-57114f71dc0f)

**Comment by ScalarVector1** [comment]
Fixed in 0.1.2
