### ISSUE TITLE
[Bug] Bricklayer's Trowel eats up Living Wood Wand, Leaf Wand (and possibly other Block-Placing Wand)

### ISSUE THREAD

**Issue by ChristianNguyen-Chinag** [ProjectStarlight/StarlightRiver#446]
Context: Bricklayer's Trowel allows you to "extend" block lines by hovering over a block, causing a block placement preview to spawn based on player's direction to it. If the player have said block in their inventory, they can hold left click and the Trowel will place blocks as far as the player wishes.

Expected Behavior: The block placement preview appears when you hover over a living wood block. The living wood block was placed by using the Living Wood Wand which consumes Wood Block in the inventory to place.
Having both the Living Wood Wand and Wood Block in the inventory, I expected the Wood Trowel to use up a wood block and place a living wood block.

Actual Behavior: Instead of consuming a wood block to place a Living Wood block, it will instead consume the Living Wood Wand itself. The wand will be consumed and a living wood block is placed by the Trowel. You can't place anymore as you no longer have the required Wand to place the special blocks.

I suspect it's because the Trowel's block placing mechanic thinks that the Wands themselves are the block that is trying to be placed, not tools that places said special blocks. Hence why the wands are consumed when trying to place them. 

I haven't tried it with other Block-placing Wands such as Bone Wand and Hive Wand, but I suspect they will fall to the same problem.

A possible solution is to add a specific behavior for the Bricklayer's Trowel regarding Block-placing Wands and the blocks they place. 

Reproduction steps:
Mod list: Starlight River v0.1, Recipe Browser v0.10, Item Magnet Plus v1.2.0.1, Calamity QoL for Vanilla v0.5.1
Default Config settings for Starlight River

1. Place a Living Wood Block or a Leaf Block using either a Living Wood Wand or Leaf Wand respectively.
2. Hover over the placed block with the Bricklayer's Trowel. A block placement preview should appear, showing that it wants to place the same block.
3. Left click to place a new block using the trowel.
4. Be sad that you just lost your loot from the vanilla big trees.

Reproduction images using the Leaf Wand block instead. It behaves the same as the Living Wood Wand and has the same bug when placing Leaves block. Notice how only the Leaf Wand in the hotbar is consumed, the amount of Wood blocks doesn't change after placement.

Before:
![bilde](https://github.com/ProjectStarlight/StarlightRiver/assets/60467963/c5ac7504-1f51-4e27-aee2-084709949681)
After:
![bilde](https://github.com/ProjectStarlight/StarlightRiver/assets/60467963/d460193c-3987-4b15-96a1-214ac5483698)

**Comment by SuperAndyHero** [comment]
Should be fixed in the next update
