### ISSUE TITLE
The camera stays focused on the middle of the Cerios arena for about 30 seconds after they're summoned

### ISSUE THREAD

**Issue by davicslavic42** [ProjectStarlight/StarlightRiver#45]

**Comment by bobfishkins23** [comment]
Please submit a proper error report, with repo steps and expected VS resultant behavior.

**Comment by davicslavic42** [comment]
After right-clicking on the boss skull to spawn cerios the camera pans up to the center of the arena as cerios has the startup animation; but once he starts attacking the player the camera stays focused on the center of the arena where cerios was, until around 30 seconds later when the camera then refocuses on the player. VS: I was expecting that once cerios started attacking the player the camera would then focus on me. Instead, the camera stayed focused on the center of the arena for around half a minute before later refocusing on me

**Comment by bobfishkins23** [comment]
I cant seem to reproduce this, are you possibly playing with frame skip on? could you try again with frame-skip disabled?

**Comment by davicslavic42** [comment]
I tested again and it works better now, so the issue was just frame skip
