### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Mamoog** [ProjectStarlight/StarlightRiver#458]
## When attempting to speak to the Glassweaver it is impossible to pick a dialogue option
I don't know what's supposed to happen since it's my first time trying, but when 
clicking a response literally nothing happens. I don't know if it's because i'm using cheat sheet and hero's mod as i was just exploring the features.

The mods i had on were just starlight river, cheat sheet and hero's mod. all configurations on the mods were normal. 

## Reproduction
The mods i had on were just starlight river, cheat sheet and hero's mod. all configurations on the mods were normal.
I was legit just standing still and tried speaking to him.
OS: I was on windows 10

**Comment by Hioia** [comment]
The same happens to me just with the crow npc (or whatever his name is) and I couldn’t get out unless i died and even if i died i was invincible to all damage except a few like lava or fall damage and if i grappled the cutsene restarts so i can’t really have a normal playtrough further

**Comment by EnderMaster77** [comment]
this shouldve been fixed in 0.1.2. Make sure to update your starlight river mod.
