### ISSUE TITLE
Null ref when reloading after enabling other mods[Bug]

### ISSUE THREAD

**Issue by Lostmaniac9** [ProjectStarlight/StarlightRiver#460]
Expected behavior: **The game reloads all mods correctly without issues.**
Actual behavior: **A crash occurs every time I reload mods even if the mods are compatible. If I choose exit and come back into the game the mods are even loaded correctly.**
Context: **It occurs every time I enable a single other mod and then hit back to reload them.**
Error message (if applicable): ![image](https://github.com/ProjectStarlight/StarlightRiver/assets/26028438/28b4cded-170f-4940-bf87-606907885c10)

Mod list: **Only Starlight River and Cheat Sheet were enabled when I first got this to happen. Doing it with any other mods (and any number of mods) causes the exact same issue.**
Config settings: **Default**
		
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11646695/client.log)

**Comment by ScalarVector1** [comment]
Fixed in previous versions
