### ISSUE TITLE
Barrier effect is offset from character

### ISSUE THREAD

**Issue by Mann390** [ProjectStarlight/StarlightRiver#461]
So I just got the barbed knife with barrier. An effect appeared that was a copy of my character that was sort of pulsing. I expected it to instead be on my character to look like the character itself was pulsing, but it instead offset itself making it look weird. I have starlight river, recipe browser, wing slot, achievement mod, shoe slot, favorite mark, menu title splash, and advanced world gen. You should be able to replicate this by either using the plated barbed knife or just by getting anything that gives you barrier.
![Capture](https://github.com/ProjectStarlight/StarlightRiver/assets/135558348/ec0b1d1d-ad7d-4de3-bbbc-8d732498ae8b)

**Comment by ScalarVector1** [comment]
Fixed in 0.1.2
