### ISSUE TITLE
[Bug] Touchstone Mining Speed Bug

### ISSUE THREAD

**Issue by robhd4k** [ProjectStarlight/StarlightRiver#463]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
The Aurora Spirit actually slows down my mining speed instead of increasing it

## Reproduction
		Mod list: Recipe Browser, Goats Render Optimizer, Where's My Items, Shorter Respawn Time, Armament Display Lite, Better 
                Extractinator, Improved Item Info
		Config settings: Default
	        Game settings: Quality: High, Frame Skip On, 1080p Borderless, Color Lighting, 100% Zoom
                Your inputs: The mouse button.
		OS: Windows 10

**Comment by Biverom** [comment]
Fixed in last patch
