### ISSUE TITLE
Indoor Overlay Darkens when Enabling Autopause

### ISSUE THREAD

**Issue by Lampshaede** [ProjectStarlight/StarlightRiver#47]
## Indoor Overlay Darkens when Enabling Autopause
	Expected behavior: game pauses
	Actual behavior: game pauses AND Darkens all Indoor walls as if you're outside of them

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River
		Config settings: Default Starlight River Config
		Game settings: 1920x1080, borderless window, autopause on+off, 
		Your inputs: Unreliably: escape, autopause on, wait half a second and the walls darken
		OS: Windows 10

## Additional context and log files
![image](https://user-images.githubusercontent.com/33045275/137255778-18b5bffc-ca31-4382-83e9-4fb70f886f0a.png)

**Comment by ScalarVector1** [comment]
Fixed in 064ee652761fcc41bcd74f0dabd5b5da87775391
