### ISSUE TITLE
[Minor Bug] magmite vacpack + jade stopwatch firerate issue

### ISSUE THREAD

**Issue by gobbeldeegoop** [ProjectStarlight/StarlightRiver#472]
## Issue Description
    Expected behavior: The magmite vacpack firing at an increased rate.
    Actual behavior: It shot so much faster than what is supposed too.
    Mod list:Starlight River v0.1.2 (the wings in the image are a part of tmodloader)
    Reproduction: Equip the jade stopwatch and star firing the vacpack.

![image](https://github.com/ProjectStarlight/StarlightRiver/assets/135607740/91029aad-5bf1-43a8-ba53-7838ad645bb1)
i have no idea what is causing this to happen but it seems to only be with this weapon.

**Comment by TripleFate** [comment]
fixed in #611
