### ISSUE TITLE
[Minor Bug] Aurora Curiosity

### ISSUE THREAD

**Issue by Astarrix** [ProjectStarlight/StarlightRiver#473]
Expected behaviour: After clicking the touchstone in the underground ice biome, I'm given Aurora Curiosity, which increases mining speed whilst looking for Auroracle
    
    Actual behaviour: After clicking the touchstone in the underground ice biome, I'm given Aurora Curiosity, decreased my mining speed massively.
    
    Mod list: Starlight River, Recipe Browser
    
    Reproduction: Click the touchstone & mine.

**Comment by GoodDays13** [comment]
you should rename this to include decreased mining speed in the name
