### ISSUE TITLE
Accessories losing effect after changing loadounts

### ISSUE THREAD

**Issue by Cris271204** [ProjectStarlight/StarlightRiver#474]
## When you change loadouts, some accessories lose their effect.

	Expected behavior: Accessory effect should remain working.
	Actual behavior: Effect simply disapeared.
	Context: Everytime the currently loadout is changed.
	Error message: None.

**Comment by ScalarVector1** [comment]
@TripleFate can you confirm if this has been resolved?

**Comment by TripleFate** [comment]
fixed in 7f75316ab467e93010f12f81893330ae713c258d
