### ISSUE TITLE
Smooth lighting coarseness: Crash document

### ISSUE THREAD

**Issue by davicslavic42** [ProjectStarlight/StarlightRiver#48]
In the new build while testing I had my SLC configs set to 7, lighting: white, quality: low, Single-player world, and frame skip on; after loading in I went to the aura arena and stood on the platform and the fps was at a stable 40 until my character reached the window where you could see the upper half of the boss. The Fps dropped to 20 and then crashed right after. VS: I was expecting to see a change of fps based on the SLC settings; Instead there was a large drop and I proceeded to crash.

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/4906278/client.log)

Side note, while I was looking at random weapons for some reason you cannot use the ultra shark; I used cheat sheet to spawn it in but I could not use it, even with different types of ammo

**Comment by davicslavic42** [comment]
quick correction the fps when I got to the crash point dropped to 15 in the auro arena, not 20

**Comment by bobfishkins23** [comment]
Closing this as the feature is being completeley reworked.
