### ISSUE TITLE
Ceiros's fire breath is mis-timed, leading to the actual damage window starting in the latter half of the animation

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#48]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
The damage box of the attack isn't active during the first half of the animation, which makes dodging the attack easier, but it also leaves room to move back into the damage box after the actual animation
	Expected behavior: When Ceiros breathes on you, it hurts
	Actual behavior: When Ceiros breathes on you, it takes a moment to hurt
	Context: I suck at dodging
https://user-images.githubusercontent.com/92499684/137255855-17e1f2a4-99ed-4c9b-b0a0-67aa73f7ab11.mp4

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Mod list: SLR, HERO's Mod, Census, Recipe Browser, Boss Checklist
Config settings: Default
Game settings: Volume and Music off
Gameplay events happening: Ceiros's breathing on me
Your inputs: Nothing this time
OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7343179/client.log)

**Comment by ScalarVector1** [comment]
Fixed in d7cd418aad5f8f50c13229f704ad5ee27946473a
