### ISSUE TITLE
Stemsaw recipe

### ISSUE THREAD

**Issue by Moonseer12** [ProjectStarlight/StarlightRiver#483]
The Steamsaw's recipe is bugged, making it uncraftable 

https://github.com/ProjectStarlight/StarlightRiver/blob/master/Content/Items/SteampunkSet/Weapons.Buzzsaw.cs

This is because recipe.Register(); is missing from the bottom of the recipe.

**Comment by TripleFate** [comment]
fixed in e8ae2f1c8519591fc949ffa51b4e90c9792b27b2
