### ISSUE TITLE
[Bug] Breacher and Ivy chest plate texture issues.

### ISSUE THREAD

**Issue by JadeTheStopwatch** [ProjectStarlight/StarlightRiver#486]
Both Ivy and Breacher armour have messed up texture on the chest plate.
Jumping causes it to disappear and its constantly having the arm in the air.

## Reproduction
wear either Ivy or Breacher armour, then jump!

![image](https://github.com/ProjectStarlight/StarlightRiver/assets/135668242/e2479dcf-987f-4a56-9f51-c955a01b9ac4)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/135668242/c6909b78-6ed8-4d6f-b6e2-c54f34fc0a70)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/135668242/2d096770-2cb8-4e52-9394-084b5bebdb62)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/135668242/ff34f5a0-0873-41a5-901b-d62f87dec57f)

**Comment by Biverom** [comment]
Also Mecha chestplate (ror reference)
