### ISSUE TITLE
[Bug] Crash after attempting to start Armillary Trial

### ISSUE THREAD

**Issue by EnderMaster77** [ProjectStarlight/StarlightRiver#493]
## Issue Description
When starting the boss rush thing, instead of loading up, I get the following error:
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/107213915/3efd0b09-1915-4303-97ac-aeddc9924efb)

Terraria then crashes after pressing OK, then gives me THIS message.
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/107213915/bfc4b7d7-be25-44ca-b9e0-112e68bc778b)

I've had messages like this in my playthrough before, it didn't crash the game. Furthermore, I verified the game files then tried again, and same error.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Just starlight river.
		To reproduce the crash, start TmodLoader,press singleplayer, select a character, press armillary trail, then it crashes with the messages shown above.
		
OS: Kubuntu 23.04

## Additional context and log files
This applies to boss blitz and starlight showdown.
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11659557/client.log)

EDIT: Not fixed as of 0.1.8.

EDIT 2: A fix has been found! Apparently there's an issue with terraria where some items have capitalization errors. On windows, these problems are non-existent. However, on Unix-based systems,  files are case-sensitive, which is the reason this crash happens on linux. I would also suspect MacOS would also experience this issue.

**Comment by GummyLeeches** [comment]
I have the same error. I am on Arch Linux, so I believe this is a bug that's Linux specific

**Comment by EnderMaster77** [comment]
A fix has been found, read the second edit I made. Might close this soon.

**Comment by ScalarVector1** [comment]
Not much we can do about this, this is a tModLoader issue.

**Comment by gurglemurgle5** [comment]
Has this been fixed yet / will this be fixed? The issue has been marked as completed, however I got the same crash earlier today.
Version: 0.2.6.2

**Comment by gurglemurgle5** [comment]
> Has this been fixed yet / will this be fixed? The issue has been marked as completed, however I got the same crash earlier today. Version: 0.2.6.2

Ok nvm found the fix
In your `Terraria/Content/Images` folder, rename `TIles_650.xnb` to `Tiles_650.xnb`
