### ISSUE TITLE
[Minor Bug] Strange Forbidden Wind block clearance behavior

### ISSUE THREAD

**Issue by cazmatism** [ProjectStarlight/StarlightRiver#501]
## Issue Description
Expected behavior: The forbidden wind dash will scale up all 1 block heights as running and normal dashing does
Actual behavior: There are strange inconsistencies in this and the fodbidden wind dash sometimes refuses to clear these heights and resets player's speed to zero (rather than max running speed as is usually the case)
Mod list: Cheat sheet, Hero's Mod, SLR
Reproduction: Have a flat plain (not very necessary), then follow it up with a tile of 1 block height such that it would be easily cleared by the player when normally dashing or running, and then dash into it from various distances and various starting movement speeds. Some of these will be "blocked"

https://github.com/ProjectStarlight/StarlightRiver/assets/135525296/0fd8044a-b0d0-4a90-9fd0-9d4b398ccb60

**Comment by ScalarVector1** [comment]
Working as intended
