### ISSUE TITLE
[Bug] Bombs can permanently damage vitric temple and break the vitric silver barriers

### ISSUE THREAD

**Issue by cazmatism** [ProjectStarlight/StarlightRiver#504]
## Issue Description
Expected behavior: Bombs do not affect the Vitric temple at all
Actual behavior: 
- Bombs can irreparably destroy the Forge and the thing that gives you the Forbidden Wind. They can also similarly destroy the tiny statue things you get encounter
- Bombs can also destroy the vitric forge pillars, giving you the item and letting you place it anywhere (which is actually kind of really cool)
- The dangerous hostile enemy spawning crystals can be destroyed via bombs
- Bombs can be used on the vitric silver barriers to allow the player to break through the Vitric temple without getting the Forbidden wind ability (although this would probably be really rare in actual gameplay
- Bombs can allow the player to get the Vitric bouncer item and break through vitric spikes via bombing them
- Similarly, various furniture and background objects can be destroyed and sometimes obtained

## Reproduction
1. Create any new world
2. Enter the Vitric temple with bombs
3. Bomb all the various things mentioned
OS: Windows

**Comment by ScalarVector1** [comment]
Fixed
