### ISSUE TITLE
[Bug] NaturesGiftArtifact Asset Could not be Found

### ISSUE THREAD

**Issue by mikeymarch13** [ProjectStarlight/StarlightRiver#510]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: n/a
	Actual behavior: error occured (see attached image).
	Context:  Error occured crossing a certain region just below the jungle surface on a mine cart.
	Error message (if applicable):  Failed to load asset: "Assets\Archaeology\NaturesGiftArtifact"!

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: just starlight river
		Config settings: untouched
		Game settings: as init, other than changes in vanilla controls.
		Gameplay events happening: Error occured crossing a certain region just below the jungle surface on a mine cart.
		Your inputs: minecart towards the right
		OS: Windows 10

## Additional context and log files

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11672215/client.log)

![Nature's gift artifact failed to load](https://github.com/ProjectStarlight/StarlightRiver/assets/135770440/a5842dc8-e49b-4888-96a1-d132ac86e743)

**Comment by SkippZzMods** [comment]
are you updated to the latest version?

**Comment by mikeymarch13** [comment]
> are you updated to the latest version?

I downloaded the mod via Steam workshop like 5 hours ago, so I had assumed so (maybe there's another way to access the mod I was not aware of). I used terraria 1.4.4 beta preview for running the mod.

**Comment by ScalarVector1** [comment]
Fixed in previous version, closing
