### ISSUE TITLE
[Bug] Cannot do damage

### ISSUE THREAD

**Issue by iAlwaysCombo** [ProjectStarlight/StarlightRiver#511]
## Cannot do damage
I am not able to do damage when this mod is active. Projectiles, melee, summons, bombs, etc do 0 damage and disappear on impact (besides melee damage, it just does nothing).
	Expected behaviour: I do damage to enemies with my weapons
	Actual behaviour: Projectiles disappear and do 0 damage
	Context: After I updated my tModLoader, the mod suddenly broke and I could not do damage to enemies, including critters.
	Error message (if applicable): There was no error message

## Reproduction
		Mod list: The only mods I have loaded are Starlight River v0.14, Recipe Browser v0.10.1.2, and Basic Automated Mining v1.2.0. Whenever I turned Starlight River off I was able to do damage.
		Config settings: I had not touched the config settings when I downloaded it.
		Game settings: Lighting: Color, Quality: Auto, Background: On, Blood and Gore: On, Miner's Wobble: Enabled, Windy Environment: Enabled, Resolution: 2048x1280, Frame Skip: On
		Gameplay events happening: I loaded the world and tried to kill some enemies in the jungle but nothing was working
		Your inputs: I loaded up the world and right-clicked on a slimebush and was not able to kill them. I then head to the Jungle and realise the bug
		OS: MacBook Air (M1)

## Additional context and log files
I'm not able to find the log files, I have searched everywhere.

**Comment by ScalarVector1** [comment]
Fixed 0.1.5
