### ISSUE TITLE
Game crashing on seeing the vitric dessert biome.

### ISSUE THREAD

**Issue by cormon1** [ProjectStarlight/StarlightRiver#52]

**Comment by cormon1** [comment]
I tried 3 times, on 2 different worlds, and everytime the biome should start to be visible, the game stopped responding and i had to close it

**Comment by bobfishkins23** [comment]
this issue is caused by the old smooth lighting coarseness setting being set to zero (you cant divide by zero :P), this feature is getting removed/replaced in the next build so im closing this for now.
