### ISSUE TITLE
[Softlock] Glassweaver Gauntlet Glitched

### ISSUE THREAD

**Issue by Mifexer** [ProjectStarlight/StarlightRiver#521]
Expected behavior: After talking to the glassweaver and accepting the challenge the gauntlet should start and continue until all waves are defeated.

	Actual behavior: After Talking to the glassweaver and starting the gauntlet they summoned one enemy and then left the arena
and cannot be interacted with any more.

	Context: Me and my friend started the gauntlet at the same time and it worked for me until he also accepted the challenge then the challenge stopped. We got off and rejoined the game and it did not fix the problem.

		Mod list: Boss checklist, recipe browser, Starlight river
	
		A Picture of the glassweaver after they stopped being able to be interacted with

![20230607213844_1](https://github.com/ProjectStarlight/StarlightRiver/assets/79713667/684c1397-84e9-4424-9d9e-f7729332e104)

**Comment by TripleFate** [comment]
fixed in #579
