### ISSUE TITLE
[Bug] Spiked Mail's Thorns feature can delete Ceiros' Resonant Crystals, softlocking the player

### ISSUE THREAD

**Issue by Snowbird334** [ProjectStarlight/StarlightRiver#522]
## Description
As stated in the title, having Spiked Mail equipped causes being hit to deal retaliatory damage to an entity, however this also applies to Ceiros Resonant Crystals. When one hits the player while they have barrier, it is removed from existence, and it cannot be dashed through to progress the bossfight, and the player is trapped and forced to use a recall potion or magic mirror to escape the fight.

## Reproduction
Equip a set of Moonstone Armor, and shining spiked mail. When the Ceiros bossfight starts, intentionally get hit by one of the resonant crystals. This can be done either during the fire circle, or when the boss firsts sends them out.

Once the resonant crystal(s) has been deleted, progress through the bossfight as normal.

Mod list: Only other mod is [Recipe Browser](https://steamcommunity.com/sharedfiles/filedetails/?id=2619954303)
OS: Windows 11

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11683952/client.log)

A video showcasing this behavior can be found here:
https://youtu.be/Svk7DfJTyWA

**Comment by ScalarVector1** [comment]
Fixed
