### ISSUE TITLE
[Bug] Pyroclastic Flow damages the Eterna Crystal

### ISSUE THREAD

**Issue by Snowbird334** [ProjectStarlight/StarlightRiver#523]
## Description
As said in the title, the Pyroclastic Flow weapon does damage to the eterna crystal.

## Reproduction
Equip a Pyroclastic Flow and fire it at an active eterna crystal

## Additional context
https://github.com/ProjectStarlight/StarlightRiver/assets/135730644/e7e7d232-5f0d-4a53-b9b3-46adb941f03d

**Comment by SuperAndyHero** [comment]
Fixed upcoming patch 0.2.2
