### ISSUE TITLE
Thunderbuss quick to fix issues

### ISSUE THREAD

**Issue by GreatFriend129** [ProjectStarlight/StarlightRiver#524]
### Unintended Muzzle Damage
Thunderbuss needs to set Item.noMelee = true; to stop doing contact damage with the gun itself.

### 1 Damage
Thunderbuss only deals one damage due to Projectile.damage being set to 0 at Line 535 in Weapons.Thunderbus.cs.
This was probably to prevent it from dealing damage multiple times but I think how ModifyHitNPC works got changed in 1.4.4 so it no longer functions as intended. The simplest solution would likely to use CanDamage() instead.

**Comment by ScalarVector1** [comment]
Fixed
