### ISSUE TITLE
[Bug] Debug items and Items labelled "This should not appear!" can be found in Recipe Browser Mod

### ISSUE THREAD

**Issue by TrueCalamitas** [ProjectStarlight/StarlightRiver#531]
Issue Description
	Expected behavior: Items should not have been able to be seen
	Actual behavior: Items were able to be seen

Reproduction
		Mod list: Starlight River, Recipe Browser, Census - Town NPC Checklist, Subworld Library
		Config settings: default
		Game settings: default
		Gameplay events happening: looking through the items tab using Recipe Browser mod
		Your inputs: Opened the item tab in Recipe Browser, scrolled for a bit, found debug items and items that should not appear

![20230609140507_1](https://github.com/ProjectStarlight/StarlightRiver/assets/136116066/de157ea6-b39f-4979-9c9a-5ad779a73716)
![20230609140517_1](https://github.com/ProjectStarlight/StarlightRiver/assets/136116066/1fdf5ad3-f7e9-415c-9871-13d96c0e6ec3)

**Comment by ScalarVector1** [comment]
non issue
