### ISSUE TITLE
Slimes and stuff [Minor Bug]

### ISSUE THREAD

**Issue by Saltssss** [ProjectStarlight/StarlightRiver#535]
Hello, been trying to play your mod a bit, it was a very exciting thing to see you finally make a release, but yesterday I noticed slimes started sinking to bottom of water, didn't think it an actual bug, coz yesterday's find was a very shallow pool, but today I had two ice slimes sink into some deeper water in a row instead of bouncing on top. I don't mind it much coz I don't have to deal with them, but it's still a bug. I will probably update this with other bugs and issues when I find them. 

I have also been trying some smaller mods on the side with it, most of them work, such as wing slot, summoner's shine, recipe browser and a 1.4 version of quality of life, since the 1.3 luiAFK didn't make a proper port into 1.4.

Some mods I use normal in the 1.4 version have yet to work in 1.4.4 that you use, like vein miner and such, but I don't know if the magic storage mod has trouble running in 1.4.4 or if SLR has trouble running with it, also boss checklist doesn't have your bosses. 

For now this is all I found.

**Comment by ScalarVector1** [comment]
This is a tModLoader bug.
