### ISSUE TITLE
[Bug] Glassweaver fight doesn't work in multiplayer

### ISSUE THREAD

**Issue by THE1FIREHAWK** [ProjectStarlight/StarlightRiver#538]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: You enter the room and the surrounding area gets dark
	Actual behavior: It doesn't enter, walking inside the area doesn't do anything so you can't fight the boss.
	Context: We had just talked to him and he told us to go fight him in his little room area thing

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight river, recipe browser, BAM (Better Automated Mining)
		Config settings: Default
		Game settings: Default I think
		Gameplay events happening: About to fight glassweaver, in multiplayer.
		Your inputs: just walking in
		OS: Windows

## Additional context and log files

I don't have the log files anymore, sorry.

**Comment by TripleFate** [comment]
fixed in: #579
