### ISSUE TITLE
Auroracle

### ISSUE THREAD

**Issue by Pokecreeper** [ProjectStarlight/StarlightRiver#54]
So, for one thing, I can't really place blocks fast enough in the Auroracle fight, and a two-block wide platform isn't enough to shield you, despite looking like it should be able to. The minions can also knock you straight into the laser while you're trying to shield yourself.

I'd recommend allowing the player more leeway while placing blocks. Though, I am a bit shaky, so that might just be me. Overall, Auroracle as it is seems like it'd be extremely frustrating in Master Mode, though in Expert it doesn't deal a lot of damage so its not really too frustrating there.

**Comment by bobfishkins23** [comment]
Both of these issues are already fixed on my branch (blocks are placed lower and a single layer is now fine to protect you), blame eggs for uploading a broken test build :/

**Comment by eggshellsv** [comment]
Build uploaded was on Scalie's branch, more tweaking is clearly needed for boss fight. will discuss with devs
