### ISSUE TITLE
Audio Stops Shortly after Load

### ISSUE THREAD

**Issue by Lampshaede** [ProjectStarlight/StarlightRiver#54]
## Starlight River music stops and restarts shortly after loading into a world
**A thorough description of the problem, including:**
	Expected behavior: Audio continues throughout the piece
	Actual behavior: Audio stops for ~3 seconds giving way to default terraria bgm, then restarts
	Context: Upon loading into demo world for first time

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River
		Config settings: the default config settings for Starlight River
		Game settings: 1980x1020 borderless window, autopause on
		Your inputs: load into a world and walk as usual
		OS: Windows 10

## Additional context and log files
In this clip I have just loaded into the world; I started the recording on the loading screen slightly slower than I wouldve liked
https://user-images.githubusercontent.com/33045275/137333562-bd996231-68ee-45cb-899b-a7eaf96b8ba4.mp4

**Comment by ScalarVector1** [comment]
Can you tell me if you had broken the ceiros altar in this world yet or not?

**Comment by Lampshaede** [comment]
This world was completely new. Nothing had been done

**Comment by Lampshaede** [comment]
I'm sorry actually if the altar is the thing in the middle and not the thing that you pick up, it WAS Broken

**Comment by ScalarVector1** [comment]
Fixed in 805e1ce6b3d5ce541005ea3fec3a15f1aebd6228
