### ISSUE TITLE
Mod instantly crashes as soon as I press single player[Bug]

### ISSUE THREAD

**Issue by RedIsYourDad** [ProjectStarlight/StarlightRiver#556]
## Mod doesn't work
**A thorough description of the problem, including:**
	Expected behavior: open single player screen
	Actual behavior: crash
	Context: playing on steam deck
	Error message (if applicable): System.IndexOutOfRangeException

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: only starlight river
		Config settings: nothing changed 
		Game settings: frame skip subtle and color lighting
		Gameplay events happening: hitting the single player button
		Your inputs: I hit the single player button
		OS: Steam deck

## log files

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11814117/client.log)

**Comment by VampiricCookie** [comment]
did you manage to fix this issue? having the same problem right now

**Comment by RedIsYourDad** [comment]
sadly not, don't know why it got closed as completed

**Comment by VampiricCookie** [comment]
actually i managed to fix it, i think my problem was that i had characters which used [i:xxx] in their name to show a certain item in the name, after i deleted those characters it worked again.

**Comment by RedIsYourDad** [comment]
wait, i played with friends on 1.4.3 and i also have a character like that...

**Comment by RedIsYourDad** [comment]
HOLY SHIT YOU JUST SAVED MY LIFE THANK YOU!!!!

**Comment by VampiricCookie** [comment]
no problem mate haha
