### ISSUE TITLE
[Bug] Item not supposed to appear

### ISSUE THREAD

**Issue by 15Bri** [ProjectStarlight/StarlightRiver#558]
I dug down in the crimson and came across a small shrine looking structure (see below images) inside was an item that isn't supposed to appear and it said to report it here.

## Reproduction
		Mod list: Starlight River, Subworld Library, Boss Cursor, Boss Checklist, Recipe Browser, Wing Slot Extra, Shoe Slot, Cheat Sheet, Worldgen Previewer, Shorter Respawn Time, No Pylon Restrictions, Compare Item Stats.
		Config settings: default
		Game settings: default
		Gameplay events happening: mining
		Your inputs: N/A
		OS: Windows 10

![image](https://github.com/ProjectStarlight/StarlightRiver/assets/137568643/a71ab062-f6c9-40ae-a7b7-826213fbb2f9)

![image](https://github.com/ProjectStarlight/StarlightRiver/assets/137568643/68db344f-66d4-453c-9ccc-018a383ab163)

**Comment by SuperAndyHero** [comment]
This item is being used as a icon that shows up when you hover, the icon shows what you need in order to break the tile. When broken this item does not drop and you never see this text without cheat mods.
not a bug.
