### ISSUE TITLE
Crashlog: Voidsmith

### ISSUE THREAD

**Issue by davicslavic42** [ProjectStarlight/StarlightRiver#56]
This test was done in a new small world, expert, and single player. During testing I checked out the void smith, I opened his tabs and clicked upgrade, the tab opened for a split second then the game proceeded to crash. VS: I expected that after opening the upgrade tab for the void smith I would see the UI with the two placeholder quests; Instead I opened the upgrade tab and then proceeded to crash.

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/5009438/client.log)

**Comment by bobfishkins23** [comment]
in this play session, had you generated or opened any worlds before this world?

when did you make your character?

did you see any error messages in chat when loading the world?

**Comment by davicslavic42** [comment]
In the play session which was yesterday a little while after the build was released, I did not open any other worlds I only generated a new one for a build. There were no messages for any errors of sorts in the chat. Although my character was made back in July for an earlier build. One note is that the first build with the voidsmith in there were no crashes.
