### ISSUE TITLE
Doesn‘t work well when in get fixed boi[Bug]

### ISSUE THREAD

**Issue by Yundong2745** [ProjectStarlight/StarlightRiver#565]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
When I was talking to Glassweaver (first conversation), it asked me to take a look at the temple. At this point, due to the feature of the "constant seed" in the "get fixed boi" world seed, the player is considered to be in the dark and loses health rapidly.

## Reproduction
		Mod list: [starlight river；quality of life]
		Config settings: [no change]
		Game settings: [seed get fixed boi]
		Gameplay events happening: [talking to Glassweaver (first conversation)]
		OS: [Win11]

**Comment by ScalarVector1** [comment]
We have no plans to support special seeds.
