### ISSUE TITLE
minor Starfury + Mantis Technique issue

### ISSUE THREAD

**Issue by coolkid2020202020** [ProjectStarlight/StarlightRiver#575]
Upon using the Mantis Technique Accessory, (a really cool accessory) I found that the star projectiles launched by the starfury can no longer go downwards through platforms, yet can still go upwards through platforms. 

This is quite the hinderance in boss fights, where arenas are composed of platforms, and bosses such as the Eater of Worlds will usually have the player shooting downwards.

I believe that the reason for this has something to do with the Starfury's normal projectiles disappearing upon contact with a surface that is below the mouse, and the semi-solid nature of platforms. 
(I Don't really know, I'm no Terraria modder, but I just thought I could try and contribute)

The same is also true with it's 4-hit special move thing.

**Comment by ScalarVector1** [comment]
This likely will not recieve changes due to requiring special behavior for a specific item
