### ISSUE TITLE
While standing on a flat surface, Vitric Lava looks weird

### ISSUE THREAD

**Issue by ThatDamnPineapple** [ProjectStarlight/StarlightRiver#58]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Lava looks the same whether your in the air or not
	Actual behavior: 
![WeirdLava2](https://user-images.githubusercontent.com/19764704/137344887-63695720-83f3-4735-bb3d-507b8fdd5ffa.gif)

	Context: It happens anywhere in the vitric for me. Only while standing on solid ground though. Happens both in and out of lava
	Error message (if applicable): N/A

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: SLR, cheatsheat, hero's mod
		Config settings: ![image](https://user-images.githubusercontent.com/19764704/137345143-f6fca762-f098-4f12-8b30-c0f658c7f4ed.png)
		Game settings: 
![image](https://user-images.githubusercontent.com/19764704/137345227-9717fd89-4410-4d52-91fa-87da3a0cc063.png)

		Gameplay events happening: in godmode, standing near lava.
		Your inputs: Just going between pressing space and not to jump (like in the gif)
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7347290/client.log)

**Comment by ThatDamnPineapple** [comment]
Relaunching the game fixed it.

**Comment by ScalarVector1** [comment]
Cant glean anything from the logs. If you find a more consistent reproduction method please post an update with that

**Comment by ScalarVector1** [comment]
Appears to not be reproducable anymore
