### ISSUE TITLE
[Bug] Corrupted worlds

### ISSUE THREAD

**Issue by Kuroha33** [ProjectStarlight/StarlightRiver#581]
Github issues should match the following format, for ease of organization and readability.

## Issue 
**Worlds are corrupted when exiting and starting the game.**

## Reproduction
When I start a new world and play the game normally, the problem occurs when I save the world and exit the game, when I start the game again and load the map again, a screen appears saying "StarlightRiver: Error loading".

There is a solution, but it is a bit annoying to repeat it constantly when starting the game, which is to disable the mod, and load the tmodloader and then re-enable the mod again.**

**Comment by aztectornado** [comment]
Are you using other mods too? I'm having the same issue of my worlds seemingly breaking when loading the aurora water, but I'm using other mods, and wasn't sure if it was just a bizarre interaction or not.

**Comment by ScalarVector1** [comment]
https://github.com/ProjectStarlight/StarlightRiver/issues/629 seems to be the same issue
