### ISSUE TITLE
[Bug] Glassweaver bugged

### ISSUE THREAD

**Issue by PryceeCB** [ProjectStarlight/StarlightRiver#586]
Expected behavior: After you talk with glassweaver in his bossfight room he jumps up and starts a bossfight 
	Actual behavior: After he jumps up he just suddenly dissapears never to be seen again and doesn't spawn any mobs to fight
	Context: I've deleted and reinstalled the game multiple times restarted the game but every single time after I started the 
                      bossfight he just dissapears. One time I got it working that he started spawning mobs, but every single mob dissapeared 
                      suddenly without any effects after just one single hit and after around 5 minutes of this bugged gameplay the game 
                      crashed.

		Mod list: Only Starlight River mod
		Config settings: The default that the game gives you
		Game settings: The defaults
		Gameplay events happening: Was trying to fight the Glassweaver, after many bugged attempts he started spawning mobs 
                                                                which dissapeared after one hit
		Your inputs: Happened after starting the Glassweaver fight
		OS: 64-bit operating system, x64-based processor

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11990909/client.log)

**Comment by ScalarVector1** [comment]
Seems like a strange exception related to a support construct attempts to access barrier information about invalid NPCs? Might be hard to reproduce

**Comment by ScalarVector1** [comment]
scratch this, this was patched previously without documentation upon investigating blame logs. Closing this now.
