### ISSUE TITLE
Sometimes when using refractive blade, multitile crystals turn transparent

### ISSUE THREAD

**Issue by ThatDamnPineapple** [ProjectStarlight/StarlightRiver#59]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Crystals shouldn't be affected by refractive blade
	Actual behavior: ![CrystalGlitch](https://user-images.githubusercontent.com/19764704/137352648-a9b62ab4-7de5-4e6b-97f4-a2c5c6e24a49.gif)
	Context: Happened in the vitric. No boss was active
	Error message (if applicable): N/A

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: SLR, cheatsheet, hero's mod
		Config settings: 
![image](https://user-images.githubusercontent.com/19764704/137353316-a0a5dfcb-1b6e-4b48-9de2-b7b0500239de.png)

		Game settings: ![image](https://user-images.githubusercontent.com/19764704/137353271-78755f60-e019-4ef9-99cf-060a60dfad22.png)
		Gameplay events happening: Simply was in the vitric, messing around with refractive blade
		Your inputs: Right clicking
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`
**Reloading the world fixed the issue, but this exact effect happened with Gluttony in the past**

**Only happens with some, seemingly random crystals**
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7347569/client.log)

**Comment by ScalarVector1** [comment]
Confirmed to no longer occur.
