### ISSUE TITLE
Problems identified in Ceiros fight

### ISSUE THREAD

**Issue by Dual-Iron** [ProjectStarlight/StarlightRiver#59]
This issue is acknowledging several design flaws in Ceiros's boss fight. It does not provide solutions. This is prone to future edits.
* Shockwave attack
  * There's no telegraph. If you're on the left side of the screen on the floor when this happens, you can get hurt without warning,
* Sand attack
  * It repeats far too often and can trap you in a cycle of blindness once you get hit once.
  * You can't see the inward ring attack _at all_ while blinded. It's guaranteed death if you're unlucky.
* Crystal slam attack
  * If you're above Ceiros when he does this, the crystals can accelerate up into you too quickly to react.
  * The crystals stuck in the ground do damage. You can barely see they're there, and it feels unfair when you run into them and take damage and knockback.
* Vulnerability phase
  * Only one arbitrary crystal can be broken, instead of any available crystal. This is simply confusing.
  * Feels really out of place. You can sit still and be totally fine during this phase. It's like Ceiros is letting you hit him.

**Comment by Variable-X** [comment]
The first point for sand attack could probably be fixed by simply having Ceiros not use it while the player is blinded, right?
