### ISSUE TITLE
[Bug] Alican appearing freezes the Day / Night Cycle

### ISSUE THREAD

**Issue by Galaxygamer3027** [ProjectStarlight/StarlightRiver#591]
For some reason every night or two at night, Alican appears at the spawning point (even if he has nothing new to say).

If every player is not at the world's spawnpoint when this happens, his visual effect (the glowing wind and special music) begins and the day / night cycle freezes so that it is always midnight. These effects continue until the host exits the world. This happens whether or not any players see or interact with Alican.

This is annoying because it causes nighttime enemies to spawn constantly, which especially hinders building and surface exploration. I've had to essentially box a large area every time I want to build anything, since I'm relatively early in the run.

So far the only Starlight power I have is Starsight, and Alican always mentions looking for someone else, which I assume is filler text. I'd be fine with him constantly appearing and changing everything up if he at least didn't freeze the day / night cycle or didn't do it so often.

**Comment by SuperAndyHero** [comment]
This should be fixed in latest patch (0.2.2)
