### ISSUE TITLE
Vitric Crystals having small spacing issues

### ISSUE THREAD

**Issue by CptZucchini** [ProjectStarlight/StarlightRiver#63]
Vitric Crystals are spawning a bit too close to each other resulting in some crystals losing half their sprite to clipping

**A thorough description of the problem, including:**
	Expected behavior: [Crystals should likely generate in clusters with some spacing in between individual crystals I imagine]
	Actual behavior: 
![Capture](https://user-images.githubusercontent.com/92538063/137359319-ae3f52ab-5223-4b56-9800-adb0a52f75e5.PNG)
	Context: [Was testing on the 2nd demo build released on 10-14 @ 12AM]

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: [SLR Demo Build, Boss Checklist, CheatSheet]
		Config settings: 
![SLR Config](https://user-images.githubusercontent.com/92538063/137359521-25f48516-3be0-406d-8928-d75fdca4c6b7.PNG)
		Game settings: N/A
		Gameplay events happening: Testing the refractive blade's right click near multitile crystals to confirm a previously reported bug, had only broken the vitric crystal containing the boss spawn altar
		OS: WIndows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7347864/client.log)

**Comment by ScalarVector1** [comment]
should be fixed in a441e99da6a0f6af8401db96e9f1148c2d12f595
