### ISSUE TITLE
Midas Prime & Crackshot Colt Don't Crit w/ S.R. mod

### ISSUE THREAD

**Issue by Storm2103** [ProjectStarlight/StarlightRiver#632]
## Issue Description
	Expected behavior: After 22 frames have passed, when a coin is shot a crit is guaranteed.
	Actual behavior: no crit at all
	Context: https://discord.com/channels/225030931008847874/1136357927658205265 (Calamity Bug reports forum, the bug only happens when SLR is on)
	Error message (if applicable): nothing in the log file unfortunetely

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
See: Context, everything you ask for in this section is on that post, yes even the config files

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/12243880/client.log)

(I assume that a log file being physically in here is mandatory, just like in the Calamtiy Bug forums so there it is despite it also being in the context link)

**Comment by TripleFate** [comment]
what accessories are you using with this? we have a few accessories in SLR that disable crits when used (their tooltip should say this though)

**Comment by ScalarVector1** [comment]
This should be resolved with 0.2.2
