### ISSUE TITLE
[Minor Bug] Blood Amulet 2nd feature not working

### ISSUE THREAD

**Issue by 0Endo1** [ProjectStarlight/StarlightRiver#633]
## Issue Description
A thorough description of the problem, including:
    Expected behavior: The text of the Blood Amuelt reads, "These bolts damage enemies and guarantee they drop life hearts on death"
    Actual behavior: The problem lies in the fact that after the bolts have damaged enemies when the enemy dies they drop 0 life hearts. It seems that the Amulet may cause the opposite effect of dropping life hearts, they may actually make it so no life hearts can be dropped, as none have after equipping this amulet.
    Mod list: plentiful ores v6.0.2
Ore excavator (1.4.3/1.4.4 Veinminer) v0.8.5
Recipe browser v0.10.1.3
DragonVault v1.1.1
Starlight River v0.2.0
    Reproduction: Equip the Blood Amulet, take 25 damage, allow the blood bolt to hit an enemy, kill the hit enemy, watch as no hearts drop.

**Comment by TripleFate** [comment]
fixed in #674
