### ISSUE TITLE
Thousandth degree[Bug]

### ISSUE THREAD

**Issue by ShindomaAzuriha** [ProjectStarlight/StarlightRiver#634]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: [The game was supposed to run]
	Actual behavior: [The game crashed]
	Context: [In multiplayer with one other player. We recently cleared skeletron and started entering the dungeon to grab bones to craft the thousandth degree. As soon as I got it I went back to the dungeon to do some more looting. Two things were noted by the weapon when each player used it. For my experience, as the server host via steam, the person I'm playing with launched the saw out and it caused my screen to show sparks, lights, vibrating/shaking, and extremely loud block breaking sounds. When I was using the weapon the person I was playing with reported vibrations to the point of making the game unplayable. Eventually after using this weapon the game would Main engine crash.]
	Error message (if applicable): [Main engine crash]

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: [plentiful ores v6.0.2
Ore excavator (1.4.3/1.4.4 Veinminer) v0.8.5
Recipe browser v0.10.1.4
DragonVault v1.1.1
Starlight River v0.2.1]
		Config settings: [default]
		Game settings: [default]
		Gameplay events happening: [We recently cleared skeletron and started entering the dungeon to grab bones to craft the thousandth degree. As soon as I got it I went back to the dungeon to do some more looting. Two things were noted by the weapon when each player used it. For my experience, as the server host via steam, the person I'm playing with launched the saw out and it caused my screen to show sparks, lights, vibrating/shaking, and extremely loud block-breaking sounds. When I was using the weapon the person I was playing with reported vibrations to the point of making the game unplayable. Eventually after using this weapon the game would Main engine crash.]
		Your inputs: [Holding out the weapon with left click and running around taking out mobs, occasionally releasing it.]
		OS: [Edition	Windows 10 Home
Version	22H2
Installed on	‎7/‎13/‎2023
OS build	19045.3208
Experience	Windows Feature Experience Pack 1000.19041.1000.0
]
[server.log](https://github.com/ProjectStarlight/StarlightRiver/files/12247505/server.log)

## Additional context and log files
**I did attempt to recreate the issue in single-player and wasn't able to get it to crash.** 

Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Steam\steamapps\common\tModLoader\tModLoader-Logs`

**Comment by TripleFate** [comment]
your log file is 0 bytes and is only the server.log. make sure you include both client.log and server.log if possible

**Comment by ShindomaAzuriha** [comment]
[server.log](https://github.com/ProjectStarlight/StarlightRiver/files/12247790/server.log)

**Comment by TripleFate** [comment]
fixed in #674
