### ISSUE TITLE
Auroracle crashes the game upon death. [Bug]

### ISSUE THREAD

**Issue by p0y0** [ProjectStarlight/StarlightRiver#637]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
Game crashes upon killing Auroracle.
	Error message: System.NullReference.Exception: Object reference not set to an instance of an object.

## Reproduction
The Crash happens after I kill him, but how long it takes seems to be random. I've had it crash the instant he died or up until, I assume, he would drop his stuff. I've tested this about 6 times and it's crashed every single time.
		Mod list: Only content mod is Starlight River. Everything else is QoL, like Recipe Browser and Boss Checklist.
		Config settings: Default
		Game settings: Default
		OS: Windows 10

## Log file
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/12263881/client.log)

**Comment by SuperAndyHero** [comment]
Fixed upcoming patch 0.2.2
