### ISSUE TITLE
Magmites' sprite is misaligned with their hitbox.

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#64]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
On turning around, instead of smoothly turning they suddenly snap to a visually different spot. This has also affected their status when hovering.
	Expected behavior: little bubbly boi turns around smooth
	Actual behavior: little bubbly boi gets whiplash
	Context: little bubbly boi wanted to hug me

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Mod list: HERO's Mod, Census, Boss Checklist, Recipe Browser, SLR
Config settings: Default
Game settings: God mode enabled
Gameplay events happening: Enemies moving or not moving, depending on the test situation
Your inputs: Good ol' fashioned Right Click
OS: Windows 10

**Comment by ScalarVector1** [comment]
Fixed in 4d32ea2d9dedf151216f3f85d3ee0f1408d5d5d7
