### ISSUE TITLE
[Bug] Vitric desert biome crashes game after short time

### ISSUE THREAD

**Issue by lynchboy15** [ProjectStarlight/StarlightRiver#646]
Every time I get to the vitric desert in pre-hardmode to try and take on the glassweaver boss, my game hard crashes and loses saved progress from last save point. 
Mod list: Starlight River v0.2.4
               Auto Trash v0.7.0.3
               Recipe Browser v0.10.1.5
               TCheats v0.3.0.3
               Friendly NPCs Don't Die v0.3
               Ore Excavator v0.8.5
               Subworld Library v2.2.1.2
               BossHealthBar v.01.3.1
               Shorter Respawn Time v1.1.1.2
               Begone, Evil! v1.3.0.2
               AlchemistNPC Lite v1.9
               Boss Checklist v1.6.11
               Boss Cursor v3.0.0
               Lights and Shadow v1.2.3
               Wing Slot Extra v1.3.6
               Basic Automated Mining v1.2.0
![Crash](https://github.com/ProjectStarlight/StarlightRiver/assets/141671086/682a1bf6-cefc-4c10-aeba-d46f14d23aa0)
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/12283947/client.log)

**Comment by illigerofthewest** [comment]
can confirm, this happens to me too

**Comment by Dark-Dragoon** [comment]
I am getting this same crash as well.

**Comment by Dkrisky79** [comment]
I am having this sam issue, anytime I get close to the vitric desert the background changes and what I think are enemies of the vitric desert begin to spawn in the underground desert around me. There's no issue and then the second I drop into the vitric desert my game crashes. I've tried multiple times and it's always as soon as I enter my game crashes. The only other mod I am using is the Ore Miner / Vein Miner mod

**Comment by Dkrisky79** [comment]
I just logged into the 0.2.4.2 version of Starlight River and am no longer running into this issue
