### ISSUE TITLE
[Minor Bug] Cloudstrike multiplayer lag

### ISSUE THREAD

**Issue by dolphinturtlebread** [ProjectStarlight/StarlightRiver#653]
## Issue Description
Hi there,

Me and a friend are playing Starlight River on multiplayer.

Whenever one of us fires cloudstrike, the magic lightning rifle, it severely lags the other person's game to the point of stopping. After a bit, the lag does resolve, and we can continue playing, but otherwise unusable in multiplayer.

**Comment by TripleFate** [comment]
fixed in #674
