### ISSUE TITLE
[Minor Bug] Stone of The Drowned Causes Crash When Equipped

### ISSUE THREAD

**Issue by DenverNova** [ProjectStarlight/StarlightRiver#662]
If you equip the Stone of the Drowned with 0 Barrier it causes the game to crash. Adding a different accessory first that provides barrier seems to allow you to equip Stone of the Drowned without crashing.

**Comment by ScalarVector1** [comment]
Since I cant reproduce this and no crash logs were provided I'm going to have to close this. If you're able to reproduce this again please submit a properly formatted report with logs attached.
