### ISSUE TITLE
[Bug] Auto Select doesn't pull the right row of inventory

### ISSUE THREAD

**Issue by SuchOptions** [ProjectStarlight/StarlightRiver#665]
Information dump:
tmodloader: v2023.8.3.0
terraria: v1.4.4.9
Starlight River v0.2.6
OS: Windows 10 Pro
Config Settings: Everything on Default
Controls: No Starlight River specific controls were assigned; The only change from default is x = quick heal and mouse4 = smart cursor
All issues were encountered in single player and testing was done there as well. I have not done any multiplayer testing.
Date of testing: 02.10.2023 (= 2nd of October 2023)

Since the latest version (see above), the "auto select" feature of vanilla terraria has been acting weirdly when playing with Starlight River. I first noticed it when playing with a multitude of mods, but isolated it down to Starlight River. Specifically, when trying to use the auto select feature, the game will always try to use the item in the hotbar, even if the actual item is located outside of it. The hotbar slot used is in the same column as the expected item. If the item is in the hotbar, no unexpected behaviour will occur. Outside of this, which row the item is in does not affect the outcome. The preview of the item to be used is still accurate.

Additional testing:
When holding down the auto select key, pointing the cursor at a spot where an item (for example a torch) would
be placeable, then holding down the mouse button to place the item, the player character will appear to place the item, but the item will not be placed (also not consumed). If you now keep holding the auto select key, Mouse1 and then scroll down (similar too cycling 
through the hotbar) you will select the torch and be able to place it until you let go of Mouse1.
This test was done with the torch outside of the hotbar.

Additionally, whilst the inventory is open, no unexpected behaviour occurs.

The Log of me going into a rather vanilla world and reproducing the issue (in this world no Starlight River worldgen was done):
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/12778394/client.log)

If there are any questions or additional information I can provide, feel free to message me on Discord. I can't guarantee when I will answer messages on GitHub, but I will most likely answer in seconds on Discord.
(ID tag thingy: resisbence) (I am also on the Starlight River Discord)

**Comment by Librv** [comment]
Can confirm, and it is really annoying. Here is a quick and dirty (and very low quality) demonstration.

https://github.com/ProjectStarlight/StarlightRiver/assets/73041325/370090b4-a3e2-442e-936f-d7ffd7e87e51

**Comment by Areorah** [comment]
Holding shift to fast place torches/glowsticks will cause you to instead use the item in your normal hotbar. For instance, if you have torches in column 2 row 2, it will instead use the item from column 1 row 1. The conflict is happening with Lunar Veil & Starlight River (which Particle Library is a requirement.) I posted this on Lunar Veil as well for hopefully a fix.

**Comment by Areorah** [comment]
I am having the same issue as well. Holding shift to fast place torches/glowsticks will cause you to instead use the item in your normal hotbar. For instance, if you have torches in column 2 row 2, it will instead use the item from column 1 row 1.

**Comment by Dragonisser** [comment]
Same. Been driving me crazy.

**Comment by TripleFate** [comment]
fixed in #673
