### ISSUE TITLE
game crashing when going in character select screen

### ISSUE THREAD

**Issue by dottedboxguy** [ProjectStarlight/StarlightRiver#68]
**A thorough description of the problem, including:**
	Expected behavior: not crash and open the menu
	Actual behavior: game crashed instantly when i clicked the character select button on the main screen
	Context: based on graydee, it should be the ability modifiers doing that, i in fact had the blink modifier 
	Error message (if applicable): 
![image](https://user-images.githubusercontent.com/92449077/137364796-daccc51e-5f53-484b-bd36-3330205bf77a.png)

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: starlight river (new demo), HERO's mod and autotrash
		Config settings: no change at all
		Game settings: no change
		Gameplay events happening: main menu, clicking on character select button
		Your inputs: give myself the blink ability modifier via HERO's mod cheat menu, equip it, close game, install new version of the mod, relaunch, click on character select button

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7348074/client.log)

**Comment by ScalarVector1** [comment]
Should be fixed in 7626669b58e04edc3cbd795709683b7a11d23b37
