### ISSUE TITLE
[Minor Bug] ElectroArrow Tooltip Null Reference

### ISSUE THREAD

**Issue by dudeawsomeness1** [ProjectStarlight/StarlightRiver#687]
## Issue Description
Expected behavior: I don't know what was supposed to happen.
Actual behavior: I was hitting a dummy with a spear from my mod when the error popped up in the chat. The world is unnexplored, as it is just my test world.
Reproduction: Obviously it has something to do with this ElectroArrow Tooltip, which probably showed up in Cheat Sheet, as I had no such items.
Mod list:
1. Auto Reforge v2023.7.25
2. Better Boss Health Bar for 1.4.4+ v0.9.1
3. Boss Checklist v2.1.3
4. Cheat Sheet v0.7.5
5. Begone, Evil! (Disable Evil Biome Spread) v1.3.0.2
6. A simple mod I am working on; it only adds three items and an NPC so far
7. absoluteAquarian Utilities v1.0.5.1
8. Magic Storage v0.6.0.3
9. More Accessory Slots (More Accessories) v1.4.2
10. Pylons Prevent Evils v1.9.1
11. Starlight River v0.2.7
12. Subworld Library v2.2.2.1
13. [c/EC1B9D:The Stars Above] v2.0.4.0
14. Summoner UI (Latest Stable Release) v1.2.1
15. Thorium Mod v1.7.1.5
16. Wing Slot Extra v1.4.4
17. Which Mod Is This From? (WMITF) v2.7.0

> [19:41:59.494] [Main Thread/WARN] [tML]: Silently Caught Exception: 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at StarlightRiver.Content.Items.Misc.ElectroArrow.ModifyTooltips(List\`1 tooltips) in StarlightRiver\Content\Items\Misc\Ammo.ElectroArrow.cs:line 39
>    at Terraria.ModLoader.ItemLoader.ModifyTooltips(Item item, Int32& numTooltips, String[] names, String[]& text, Boolean[]& modifier, Boolean[]& badModifier, Int32& oneDropLogo, Nullable`1[]& overrideColor, Int32 prefixlineIndex) in tModLoader\Terraria\ModLoader\ItemLoader.cs:line 2163
>    at Terraria.Main.MouseText_DrawItemTooltip(MouseTextCache info, Int32 rare, Byte diff, Int32 X, Int32 Y) in tModLoader\Terraria\Main.cs:line 17021
>    at Terraria.Main.MouseTextInner(MouseTextCache info) in tModLoader\Terraria\Main.cs:line 16795
>    at DMD<System.Void Terraria.Main:DrawPendingMouseText()>()
>    at Hook<System.Void StarlightRiver.Content.Items.Geomancer.GeomancerHood::SpoofMouseItem(Terraria.On_Main+orig_DrawPendingMouseText)>()
>    at Hook<System.Void StarlightRiver.Content.Items.Moonstone.MoonstoneHead::SpoofMouseItem(Terraria.On_Main+orig_DrawPendingMouseText)>()
>    at SyncProxy<System.Void Terraria.Main:DrawPendingMouseText()>()
>    at Terraria.Main.DrawInterface_41_InterfaceLogic4() in tModLoader\Terraria\Main.cs:line 38089
>    at Terraria.Main.<>c.<SetupDrawInterfaceLayers>b__1627_38() in tModLoader\Terraria\Main.cs:line 37998
>    at Terraria.UI.GameInterfaceLayer.Draw() in tModLoader\Terraria\UI\GameInterfaceLayer.cs:line 45
>    at DMD<System.Void Terraria.Main:DrawInterface(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
>    at Hook<System.Void StarlightRiver.Content.Backgrounds.StarlightRiverBackground::DrawOverlay(Terraria.On_Main+orig_DrawInterface,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
>    at StarlightRiver.Core.Systems.DebugSystem.DrawDebugMenu(orig_DrawInterface orig, Main self, GameTime gameTime) in StarlightRiver\Core\Systems\DebugSystem.cs:line 19
>    at Hook<System.Void StarlightRiver.Core.Systems.DebugSystem::DrawDebugMenu(Terraria.On_Main+orig_DrawInterface,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
>    at StarlightRiver.Core.Systems.ForegroundSystem.ForegroundHook.DrawForeground(orig_DrawInterface orig, Main self, GameTime gameTime) in StarlightRiver\Core\Systems\ForegroundSystem\ForegroundHook.cs:line 29
>    at Hook<System.Void StarlightRiver.Core.Systems.ForegroundSystem.ForegroundHook::DrawForeground(Terraria.On_Main+orig_DrawInterface,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
>    at SyncProxy<System.Void Terraria.Main:DrawInterface(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
>    at DMD<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
>    at SyncProxy<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
>    at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52843
>    at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52830
>    at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
>    at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
>    at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
>    at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
>    at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
>    at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 213
>    at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 78
>    at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in tModLoader\Terraria\MonoLaunch.cs:line 64
>    at System.Threading.Thread.StartCallback()

**Comment by ScalarVector1** [comment]
Please provide a full log by uploading the client.log file, not just the last few lines.

**Comment by dudeawsomeness1** [comment]
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/14489724/client.log)

**Comment by ScalarVector1** [comment]
Fixed in next update
