### ISSUE TITLE
Spawning into the demo room with forced zoom causes the room border to freak out and overlay with it's set zoom dimensions as opposed to the current zoom dimensions

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#70]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: 
![20211014132645_1](https://user-images.githubusercontent.com/92499684/137366745-b6f18308-f8a3-46a0-9719-707d7cceab6b.jpg)

Actual behavior: 
![20211014131738_1](https://user-images.githubusercontent.com/92499684/137366788-d86468fd-0ed9-423c-b8ee-1f30184bdc54.jpg)

Context: I had save-quit during the Ceiros spawning cutscene, which locked my zoom at 120%. The border didn't agree with that.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Mod list: HERO's Mod, Census, Boss Checklist, Recipe Browser, SLR
Config settings: Default
Game settings: 100% zoom (120% zoom for comparison shot)
Gameplay events happening: I load into the world and Shazam!
Your inputs: Click
OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7348153/client.log)

**Comment by ScalarVector1** [comment]
This should be fixed by extension of zoom being reset properly on relog in 817a434b244428daf18f51b6b532f29287ecd5d4
