### ISSUE TITLE
Scrapshot's grapple effect continues after death

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#71]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
When you die mid-grapple, the camera keep following the path it would have taken
	Expected behavior: The camera stops are your skull turns into a grey-matter flavor Kool-Aid receptacle
	Actual behavior: The camera carries on to finish the fight
	Context: Spittin' Snek deals a lot of damage

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Mod list: HERO's Mod, Census, Boss Checklist, Recipe Browser, SLR
Config settings: Default
Game settings: I don't know what could affect this
Gameplay events happening: I got shot, it hurt, I was not okay
Your inputs: Good ol' fashioned Right Click
OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7348224/client.log)

**Comment by ScalarVector1** [comment]
should be fixed in 68150669437f54eaed1e32aa17065fc9984e3bc7
