### ISSUE TITLE
Ancient Vitric Blade's swing continues after the weapon hits something and shatters

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#73]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The weapon's hitbox disappears after the weapon disappears
	Actual behavior: The spiteful and vengeful spirit of the blade haunts an enemy in front of you
https://user-images.githubusercontent.com/92499684/137382114-1b8034f6-5717-4fef-aa38-6ee815ec46f1.mp4
	Context: Was testing out melee weapons because I hadn't really done it before

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Mod list: HERO's Mod, Census, Boss Checklist, Recipe Browser, SLR
Config settings: Default
Game settings: Irrelevant
Gameplay events happening: Dummies were being dummies
Your inputs: Good ol' fashioned Left Clicked
OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7348827/client.log)

**Comment by ScalarVector1** [comment]
Fixed in e5e5fead92ad89a6700f3d448d43c09465ea7f2a
