### ISSUE TITLE
Blocks/Entities or modded things out of place

### ISSUE THREAD

**Issue by Nallagming2** [ProjectStarlight/StarlightRiver#730]
Expected behavior: I was loading in my multiplayer terraria world (I am the host) expecting to be normal.
Actual behavior: Some blocks were out of place (2 blocks down their original position)
Context: As soon as my tModloader loaded, i saw "Starlight River 2.7 >> 2.8"

Mod list: Thorium, QoL mods
Config settings: Default
Gameplay events happening: Just loaded the world
OS: Windows 11

This is just a normal Thorium, Starlight River multiplayer world (plus the QoL mods) but other than that, nothing else.
I think this is only from Starlight River 2.8 as i mentioned the update i saw before all this happened.

![image_2024-07-08_115152461](https://github.com/ProjectStarlight/StarlightRiver/assets/121287849/4c0ec522-1381-45cb-866a-88693e0780fb)

**Comment by Laungerton** [comment]
Know where to find an earlier version of Star-light? Having the same issue.

**Comment by ScalarVector1** [comment]
see https://github.com/tModLoader/tModLoader/pull/4287

**Comment by ryanpolasky** [comment]
+1 to this issue, occurred in just about the same circumstances as OP had.

**Comment by ScalarVector1** [comment]
Closing this as this issue is tModLoader related and should be resolved after updating to tModLoader 2024.5.3.3. Please load a backup AFTER UPDATING TMODLOADER if your world was affected.
