### ISSUE TITLE
Using certain weapons crashes the game [Bug]

### ISSUE THREAD

**Issue by ArcTheOne** [ProjectStarlight/StarlightRiver#731]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
	Expected behavior: Use the weapons (Steamsaw and Overflowing Urn) normally
	Actual behavior: Steamsaw crashed only twice when I used for the first time immediately after crafting, against a bunny and a firefly. Overflowing Urn crashes repeatedly when used.
	Context: Steamsaw crash no longer occurs, but it happened when I was using its projectile to kill a bunny and firefly. Overflowing Urn crash happens randomly when I fire it at a mob or just in the air.
	Error message (if applicable): "System.Reflection.Target.InvocationException: Exception has been thrown by target of an invocation." I will attach an image of it,

## Reproduction
		Mod list: Reduced Grinding v9.9.0.1, Bulk Extractinator v1.1.1, Starlight River v0.2.8, Basic Automated Mining v1.2.5, absoluteaAquarian Utilities v1.0.5.1, Magic Storage v0.6.0.3, Recipe Browser v0.10.7
		Config settings: Default for everything
		Game settings: Zoom 100%, UI scale 115%, Frame Skip off, Lighting: Color, Quality: High, Backgound: On, Blood and Gore: On, Heat Distortion: Enabled, Storm Effects: Enabled, Waves Quality: High, Windy Environment: Enabled
		Gameplay events happening: Steamsaw crash happened right after killing eye of Cthulhu, I was chilling testing my new weapon. Overflowing Urn crash is most common when fighting the auroracle, usually the second I fire it once the boss fight starts.
		Your inputs: Left click on top of the enemies
		OS: Windows 11 Home

## Additional context and log files
[stlr_overflowing_urn - auroracle crash.log](https://github.com/user-attachments/files/16169822/stlr_overflowing_urn.-.auroracle.crash.log)
[stlr_steamsaw - bunny crash.log](https://github.com/user-attachments/files/16169823/stlr_steamsaw.-.bunny.crash.log)
[stlr_steamsaw - fireflty crash.log](https://github.com/user-attachments/files/16169824/stlr_steamsaw.-.fireflty.crash.log)
![Starlight River Buzzsaw Crash](https://github.com/ProjectStarlight/StarlightRiver/assets/166782948/322134b3-3671-447d-941e-496682d49394)

**Comment by ArcTheOne** [comment]
Btw, the steamsaw crash is back. I can reproducibly crash the game with it during a blood moon by hitting any enemy with the projectile and the melee portion of the attack.

**Comment by ScalarVector1** [comment]
Should be fixed in 0.2.8.1
