### ISSUE TITLE
random crashes \very important/

### ISSUE THREAD

**Issue by filip1527** [ProjectStarlight/StarlightRiver#732]
The game randomly crashes 2-5 minutes after the world loads, without any observable reason. I asked other users and they report the same problem, both in singleplayer and multiplayer.
Please fix this, it renders the mod virtually unplayable.

**Comment by ScalarVector1** [comment]
I'm going to have to close this as it includes none of the required formatting nor any logs or reproduction steps, Please resubmit with these things.

**Comment by filip1527** [comment]
Hey, sorry for not answering earlier, I had to change my Google account
because of a data leak, anyway, I didn't say anything more because there
wasn't anything else to say. Starlight was my only enabled mod, and the
game crashed randomly so I couldn't really write any reproduction steps.
Other people have been complaining about this as well and there doesn't
seem to be any particular reason or pattern.
