### ISSUE TITLE
Primitive Drawing Causes Crash

### ISSUE THREAD

**Issue by ColinBurnett1999** [ProjectStarlight/StarlightRiver#735]
I'm not exactly sure what triggers the crash, but according to a Github contributor on the TModLoader Discord server primitive drawing from this mod was the cause of a crash. It's also been affecting a friend of mine I've been playing multiplayer with. Apologies if this issue post isn't formatted great as I rarely use Github and haven't made an issue report before.

	Mod list: 
		Ore Spears 1.1
		Verv's Minecraft Mod 1.0.1
		Ty's Yoyo Redux (1.4.4 Port) v1.7
		Starlight River 0.2.8
		High FPS Support 0.6.6.2
		Enemy Hit Effects Reborn 1.2
		Which Mod is This From? 1.7.2
		Secrets of the Shadows 0.24.1.4
		Spirit Mod 1.5.0.17
		Recipe Browser 0.10.7
		Better Caves 1.1.6
		Assorted Mod Compatibility 1.3.4
		Everjade 0.1
		Thorium 1.7.1.6
		Aequus (Work in Progress) 2.7.0.6
		Aequus: Music (1.4.4 BETA) 2.7
		Fargo's Mutant Mod 3.3.4.1
		Fargo's Souls Mod 1.6.10.6
		Fargo's Music Mod 0.1.5.1
		Luminance 1.0.5
		Advanced World Generation 3.1.7
		Boss Checklist 2.2.1
		Infrasonic 2.1.2
		tModPriorityChanger 1.3
		Hook Stats & Wing Stats 2.0.2.1
		absoluteAquarian Utilities 1.0.5.1
		MagicStorage 0.6.0.3
		
		Config settings are the defaults.
		
	Video settings:
	    Video: 
	    1920 x 1080 Resolution, fullscreen
	    Parralax: 65%
	    Frame Skip: Off
	    Lighting: Color
	    Quality: Auto
	    Background: On
	    Blood and Gore: On
	    Heat Distortion: Enabled
	    Storm Effects: Enabled
	    Waves Quality: High
	    Windy Environment: Enabled
		
I'm on Windows 11 and there doesn't seem to be any specific trigger. It happened for my friend at random times in totally different parts of the map and only happened to me once while I was in the snow biome.

[client.log](https://github.com/user-attachments/files/16202520/client.log)
[environment-client.log](https://github.com/user-attachments/files/16202521/environment-client.log)
[environment-server.log](https://github.com/user-attachments/files/16202522/environment-server.log)
[Launch.log](https://github.com/user-attachments/files/16202523/Launch.log)
[Natives.log](https://github.com/user-attachments/files/16202524/Natives.log)
[server.log](https://github.com/user-attachments/files/16202525/server.log)
[terrariasteamclient.log](https://github.com/user-attachments/files/16202526/terrariasteamclient.log)

**Comment by ScalarVector1** [comment]
These logs dont indicate a crash. Could you update to 0.2.8.1 and attempt to reproduce this again? Be sure to get the log before starting the game again as starting the game again will replace the logs with new ones.

**Comment by ScalarVector1** [comment]
0.2.8.2 should fix this

**Comment by ColinBurnett1999** [comment]
Was encountering a lot of crashes playing earlier today, then the update came out and we didn't crash once. I think 2.8.2 fixed it but if you want to check here are the crash logs.

[SR Pre-0.2.8.2 Crashes.zip](https://github.com/user-attachments/files/16261229/SR.Pre-0.2.8.2.Crashes.zip)
