### ISSUE TITLE
Moonstone meteor crash

### ISSUE THREAD

**Issue by FluffyMagicLoaf** [ProjectStarlight/StarlightRiver#738]
I had just found and made it to the moonstone meteor site and proceeded to mine some of the ore until when I silently crashed from what i had assumed to be from the Dreambeast teleporting.
I went back to mine it again until I had crashed a second time, although this time I managed to stay there for longer with all the enemies (a little too many might I add) spawning and attacking as normal.
When I went to check the log, it caught the game attempting to divide by zero from the moonstone ore tiles. 

log file:
[client.log](https://github.com/user-attachments/files/16233248/client.log)

mod list used:
[enabled.json](https://github.com/user-attachments/files/16233268/enabled.json)

Lemme know if I seemed to have missed something to tell, I just wanted to bring this to light cause I didn't see another report like this here

**Comment by ScalarVector1** [comment]
0.2.8.2 should fix this
