### ISSUE TITLE
[Bug] My game crashes after geting the powerup dash 

### ISSUE THREAD

**Issue by IsTaneki** [ProjectStarlight/StarlightRiver#739]
Github issues should match the following format, for ease of organization and readability.

I was playing a normal playthrought till the cristal temple belllow the desert, after I defeated the forge guy I went to explore the templo.
All was normal till i get to a room after breaking some glass pannels. til the exact part on the image an my game always crash and I tried this with and whithout others mods.

My game sttings were:

resolution: 1920x1080
parallax: 60
no skip frames
ilumination: color
quality: high
with background
enable gore and blood
miner's wobble: on
windy environment: on

Im playing on windows 11

LOGS
[2023-10-15-79.zip](https://github.com/user-attachments/files/16237874/2023-10-15-79.zip)

Where it chrash 
![imagen_2024-07-15_185610903](https://github.com/user-attachments/assets/c8ef9820-1a89-46d6-b070-02bfbc5e8870)

Sorry if its confusing I have the game on another language and first report.

**Comment by ScalarVector1** [comment]
0.2.8.2 should fix this
