### ISSUE TITLE
Sneks can warp into a lava pool and die

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#74]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Sneks would either avoid lava or not take damage from it
	Actual behavior: Sneks are idiots and drown on extra-spicy water
	Context: I was testing something for Graydee and the sneks I spawned were idiots

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Mod list: HERO's Mod, Census, Boss Checklist, Recipe Browser, SLR
Config settings: Default
Game settings: Irrelevant, I just stood there
Gameplay events happening: Sneks warpin' around
Your inputs: Good ol' fashioned standing still
OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7348928/client.log)

**Comment by ScalarVector1** [comment]
Should be fixed in 08c2ef690bc1699b4896200155635f264fdf5049
