### ISSUE TITLE
[Bug] Wrong sprite used for Thousandth Degree wheel projectile

### ISSUE THREAD

**Issue by AXLV98** [ProjectStarlight/StarlightRiver#745]
Behavior:
![泰拉瑞亚：我只想知道金子在哪？ 2024_7_30 2_45_39](https://github.com/user-attachments/assets/85b8006c-5f96-46e5-b205-1e644efd47bd)
![泰拉瑞亚：我只想知道金子在哪？ 2024_7_30 2_45_35](https://github.com/user-attachments/assets/78efb6ee-531e-4949-9853-6432164e77b2)
Game settings:
![泰拉瑞亚：也试试饥荒吧！ 2024_7_30 2_46_44](https://github.com/user-attachments/assets/a5bb54e3-8614-4762-b3f3-499058bb80fd)
Config settings: Starlight River is the only one.
Your inputs:This is what it looked like when I got it
OS: Windows 10

**Comment by Nestorboy** [comment]
This has been fixed as of 0.2.8.3
