### ISSUE TITLE
[Bug] Economy Breaking Item

### ISSUE THREAD

**Issue by INekouo** [ProjectStarlight/StarlightRiver#748]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**

	Expected behavior: [what was supposed to happen?]
it was supposed to not break the game economy and force everyone in my group to delete spring vines and platinum

	Actual behavior: [what did happen?]
	SPRING VINES Sell values are absurd
	
	Context: [what else happened around this? When did it happen?]
		I was casually selling items and found out why the fuck i get 1 platinum from
	Then i realised that if i sold my stock of 2K SPRING VINES i would get 1,5 PLATINUM COINS
	
	Error message (if applicable): [what did the game think was wrong?]
	not a error but a wrong value from a item absurdly easy to get

**Comment by TripleFate** [comment]
there isn't an item called "spring vine" in starlight river. make sure you report bugs to the correct mod
