### ISSUE TITLE
[Bug] Super annoying npc sound glitch/breaking

### ISSUE THREAD

**Issue by INekouo** [ProjectStarlight/StarlightRiver#749]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: [what was supposed to happen?]
	Basically i expect the sound from the npcsto not sound like a demoniac Woodpecker that everyone can hear anywhere in the map
	
	Actual behavior: [what did happen?]
	Basically the Rust NPCS
	Context: [what else happened around this? When did it happen?]
	Also i could hear my friend figthing "mechanical minor" npcs at surface while he was halfway to hell and i could heard the NPC attack and all their sounds
	
	Other make a woodpecker fast sound "Tec tec tec tec tec" that come from rust/jelly npcs sometimes from what we noticed
	
	My friend message: 
its a enemy doing that sound
a fuckingg rusty circle thing
spawn projetciel
projectile bug
make naoyying sond
i think

But yeah this get really annoying when playing with 5 peoples and kinda make experiense worse

	Error message (if applicable): [what did the game think was wrong?]

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: [what mods you have loaded]
	Starlight River ( I tested with Cheat Mod to test and comfirm )
	Cheat Sheet
	
		Config settings: [the config settings for Starlight River]
		Default
		Game settings: [the settings for the game, things such as zoom, lighting mode, etc]
		Default
		Gameplay events happening: [whats going on? were you fighting a boss? mining ores? AFKing?]
		Exploration at underground since those enemies only spawn there except jelly
		
		Your inputs: [what you did precisely to trigger the issue. EX: running to the left and using the thunderbuss to the right]
		OS: [what OS are you on?]
		As long they spawn, sometimes they do this sound randomly

**Comment by TripleFate** [comment]
I can't tell what NPC you are referring to based on this description, could you attach an image of the NPC in question? make sure it's actually a starlight river NPC

**Comment by INekouo** [comment]
mb i though STELLAR mneant star river but its lunar veil
