### ISSUE TITLE
Ceiros's spiky ball attack seems to have a vertically misaligned hitbox

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#75]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: When the spike explosion happens, I should take damage from standing under it
	Actual behavior: Standing directly under it is the safest place to be. Jumping up does cause damage.
	Context: I was testing the fight itself to figure out its flow and happened to be standing under one, noticed it didn't do damage, then proceeded to stand under it every time I could.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Mod list: HERO's Mod, Census, Boss Checklist, Recipe Browser, SLR
Config settings: Default
Game settings: God mode enabled
Gameplay events happening: Ceiros's crystal got smacked the second time, hilarity ensued
Your inputs: Good ol' fashioned standing under a dangerous thing
OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

**Comment by ScalarVector1** [comment]
Should be fixed in 987c59a28b4a01cb4a85367ee4142b0b67de96d5
