### ISSUE TITLE
Low framerates

### ISSUE THREAD

**Issue by Lord-Gewp** [ProjectStarlight/StarlightRiver#777]
The game Lags, and slows down on this computer.

    This is on Linux Mint, 21.3 Cinnamon (Version 6.0.4). The game normally lags with this mod, only a tiny bit on base game terraria, but enough to make boss fights easy. I have SLR, Heros mod, and CheatSheet. I am going to look for a mod that optimizes the game or changes the game so that it isnt all calculated on framerate. A lower quality/lower pixel count might help, but i wont interfere with your mod coding.

**Comment by ScalarVector1** [comment]
This isnt really specific enough to be actionable in any way, if you have some more information or profiler logs there may be something more we can do, but otherwise this isnt actionable.
