### ISSUE TITLE
[Bug] Glassweaver is nowhere to be found

### ISSUE THREAD

**Issue by Kinoyorigambaru** [ProjectStarlight/StarlightRiver#781]
## Issue Description
Expected behavior: Grassweavers will spawn near the arena.
Actual behavior: Glassweaver isn't spawn.
Context: Nothing in particular.
Error message (if applicable): Doesn't exist.

## Reproduction
Mod list: Calamity, the star above, thorium, spirit
Config settings: Default
Game settings: [config.json](https://github.com/user-attachments/files/18184839/config.json)
Your inputs:Nothing in particular.
OS: windows
## Additional context and log files
[client.log](https://github.com/user-attachments/files/18184871/client.log)

**Comment by live1128** [comment]
Reinstalling the mod fixed it
