### ISSUE TITLE
Ceiros crystals somewhat difficult to see during fight

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#8]
The crystals Ceiros attacks you with are quite difficult to see during the fight. Maybe add a glow effect to them to make them easier to see

**Comment by TotallyNotAScalie** [comment]
Visuals updated to have a more notice
![Glower](https://user-images.githubusercontent.com/5168952/119301655-cedd6500-bc30-11eb-940d-47e1cfc700a2.png)
able glow effect

**Comment by egshels** [comment]
Please submit a pull request before closing issues for this repository.
