### ISSUE TITLE
new weird clipping through blocks of the magmites

### ISSUE THREAD

**Issue by dottedboxguy** [ProjectStarlight/StarlightRiver#80]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: magmites should not go through the floor nor eat the crystal
	Actual behavior: 2 specific places are making the magmites go wild on glitchyness
	Context: i was messing around in the glitched generated world reported earlier, and suddenly i saw a magmite clip and getting stuck in a very specific place of the huge crystals

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: HERO's mod, latest starlight river demo
		Config setting : no changes 
		Game settings: no changes
		Gameplay events happening: i was afking behind the crystal
		Your inputs: standing still behind a big glitched crystal
		OS: windows 10 64 bit pro (i think)

## Additional context and log files
![image](https://user-images.githubusercontent.com/92449077/137518346-e071ea19-4f2d-4784-a071-7812ece02e7b.png)

[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7354579/client.log)

**Comment by ScalarVector1** [comment]
b5686b5082bd2488b16e1f65a8ac6535c4552c66 should prevent this from happening
