### ISSUE TITLE
The Breacher Set's drone will continue to hunt down enemies after the player dies, even if the original target despawns

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#82]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The drone disappears along with the player
	Actual behavior: Some poor spittin' snek got deleted by the Ghost of a ghost
	Context: I dies against Ceiros again but my drone wanted blood anyway

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Census, Boss Checklist, Mod Browser, HERO's Mod, SLR
		Config settings: Default
		Game settings: Down is "s" but I can't think of anything else that matters
		Gameplay events happening: Ceiros's spikes impaled my feet
		Your inputs: Double-tap down before spikes reached from my shoes to my shins
		OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7356533/client.log)

**Comment by ThatDamnPineapple** [comment]
Fixed
