### ISSUE TITLE
When Ceiros eats the Resonant Crystals, the magma ball can drop a heart

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#85]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The magma ball just gets eaten 
	Actual behavior: The magma ball was apparently alive the entire time
	Context: I was fighting Ceiros and I was at like 280 health

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: HERO's Mod, Census, Recipe Browser, Boss Checklist, SLR
		Config settings: Default
		Game settings: Game is on, everything else irrelevant 
		Gameplay events happening: Ceiros got hungry
		Your inputs: Playing sub-optimally
		OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7358447/client.log)

**Comment by ScalarVector1** [comment]
Should be fixed in aae7d201b50d72ad9d893e28833542b69df5b4f6
