### ISSUE TITLE
[BUG] Forbidden Wind's direction ignores confusion

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#87]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Dashing while confused will move in the opposite horizontal direction of what you're holding, in the same way you move. Alternatively, not being able to dash would solve the issue.
	Actual behavior: Dashing while confused will move in the direction you're holding, which is opposite your movement
	Context: I was testing something and noticed it.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: HERO's Mod, Census, Boss Checklist, Recipe Browser, SLR Demo Build
		Config settings: Default
		Game settings: standard WASD for movement, Shift is dash
		Gameplay events happening: A giant enemy bat approached
		Your inputs: Dashing around at a speed considerably slower than sound
		OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7358486/client.log)

**Comment by ScalarVector1** [comment]
Fixed in 3b122509b956a0e5295f9e5c731d3085a1947d59
