### ISSUE TITLE
Ceiros P2 floor spikes don't refresh Rocket Boots/X in a bottle

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#9]
Can be very annoying to escape the spikes if you don't have a grappling hook. I mean, you'd have Forbidden Winds but I'm an idiot and never thought about using it.

**Comment by TotallyNotAScalie** [comment]
Changed

**Comment by egshels** [comment]
Please submit a pull request before closing issues for this repository.
