### ISSUE TITLE
Dyes don't work when player is spinning.

### ISSUE THREAD

**Issue by CantWontDo2** [ProjectStarlight/StarlightRiver#90]
Github issues should match the following format, for ease of organization and readability.

## Issue Description

	Expected behavior: dyes apply when player is spinning (forbidden winds or twisted blade)
	Actual behavior: dyes did not apply, normal armor textures were displayed instead
	Context: I was just testing dyes on the armors, and happened to notice that player spun during the dash. When I looked closer, the dyes weren't applied.
	

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		A detailed walkthrough of how to reproduce the issue, as thorough as possible.
Mod list: Night and Day Potions, Subworld Library, Weaponout Lite, Fargo's Mutant Mod
Config settings: Screenshake: 1, Lighting Buffer Rate: 15, Extra Particles and High quality lit textures On
Game settings: Zoom 100%, Frame Skip On, Lighting Mode: Color, Multicore Lighting Off, Quality: Low, Heat Distortion and Storm effects: Off, Blood and Gore: Off, Waves Quality: Off.
Gameplay events happening: Killed Ceiros
Your inputs: Forbidden Winds, Twisted Blade
OS: Windows 10
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7361142/client.log)

## Additional context and log files
**Add any other context about the problem here.**

**Comment by ScalarVector1** [comment]
Fixed in 067e9166ba542f83a43e5bbd87b53cf9176c4892
