### ISSUE TITLE
Coalescence bug with autopause

### ISSUE THREAD

**Issue by CantWontDo2** [ProjectStarlight/StarlightRiver#91]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Coalescence shoots towards where cursor was when autopause was activated
	Actual behavior: The arrows changed trajectory sharply towards where the cursor was moved during autopause, then shot off in a different direction.
	

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Night and Day Potions, Subworld Library, Weaponout Lite, Fargo's Mutant Mod
Config settings: Screenshake: 1, Lighting Buffer Rate: 15, Extra Particles and High quality lit textures On
Game settings: Zoom 100%, Frame Skip On, Lighting Mode: Color, Multicore Lighting Off, Quality: Low, Heat Distortion and Storm effects: Off, Blood and Gore: Off, Waves Quality: Low.
Gameplay events happening: Shot Coalescence during autopause.
Your inputs: Charge Coalescence fully, go into autopause, change cursor location, go out of autopause
OS: Windows 10

## Additional context and log files

https://imgur.com/a/M18BfF6

**Comment by ScalarVector1** [comment]
Fixed in bd360ee40c515e22a480f07c3d5e6455fb802985
