### ISSUE TITLE
Issue with Fire Circle attack and autopause

### ISSUE THREAD

**Issue by CantWontDo2** [ProjectStarlight/StarlightRiver#92]
## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Fire circle looking normal with autopause activated
	Actual behavior: Trails between crystals disappeared, leaving only dust.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
Mod list: Night and Day Potions, Subworld Library, Weaponout Lite, Fargo's Mutant Mod
Config settings: Screenshake: 1, Lighting Buffer Rate: 15, Extra Particles and High quality lit textures On
Game settings: Zoom 100%, Frame Skip On, Lighting Mode: Color, Multicore Lighting Off, Quality: Low, Heat Distortion and Storm effects: Off, Blood and Gore: Off, Waves Quality: Low.
Gameplay events happening: Ceiros fire circle attack
Your inputs: Go into inventory with autopause on
OS: Windows 10
## Additional context and log files
![image](https://user-images.githubusercontent.com/92417330/137653661-b9dab2e8-4c63-49f8-99ec-ba6033c32351.png)

**Comment by ScalarVector1** [comment]
Fixed in 6a88dda975e869bc1593a093a17e686551dc53c6
