### ISSUE TITLE
Moonstone set bonus's visual, progress and activation are stored in the helmet, meaning it can gain Datsuzei's charge with only the helmet equipped, and can visually activate Datsuzei (it disappears instantly)

### ISSUE THREAD

**Issue by Anarchy-9486** [ProjectStarlight/StarlightRiver#94]
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: The armor set bonus doesn't happen at all without all the pieces equipped
	Actual behavior: The circle appears, gains charge as normal, and Datsuzei can even be summoned with JUST the helmet, although it doesn't actually become usable or have it normal visual effects.
![20211019095537_1](https://user-images.githubusercontent.com/92499684/137925939-f1ad71e0-2509-4918-b1b5-b9822689ffeb.jpg)
Context: I was swapping armor sets to test melee and noticed that the circle appeared before I put on the whole set

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Recipe Browser, Boss Checklist, Census, HERO's Mod, SLR 
		Config settings: Default
		Game settings: Normal gameplay settings
		Gameplay events happening: Moonstone Helmet equipped, nude otherwise
		Your inputs: Doube-tap down like normal
		OS: Windows 10

## Additional context and log files
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/7373956/client.log)

Edit: After further testing, trying to activate the ability without the full armor set equipped queue's it up for when you actually equip the full set. A minor issue that disappears if the rest of the bug is fixed, but one to be mentioned for sure.

**Comment by ScalarVector1** [comment]
Fixed in 7e87b88aeb0913905dd2edf94ca7169b1f69b3be
